### ISSUE TITLE
execution of existion tcl

### ISSUE THREAD

**Issue by motiurce** [rclab-auth/gidopensees#100]
Hi,
In Gid+OpenSees, I can import geometry from existing tcl. But I want to run existion tcl (full model) and view the result in post processor. is it possible by using Gid+OpenSees interface? or any suggestion?

**Comment by vpapanik** [comment]
Yes, since the model geometry is imported, you have to manually enter the rest of the model data (materials, sections etc). In the upcoming version it will be a better import feature which will incorporate some of these data.
