### ISSUE TITLE
Surface element tab

### ISSUE THREAD

**Issue by atharv96** [rclab-auth/gidopensees#102]
Hi.....I am not able to open the surface element tab in GiD+OpenSees interface? When I click on it, software doesn't show any error message or anything? However force-displacement element tab and volumetric element tab are working properly. Please educate me with this problem. Thank you!

**Comment by theokart** [comment]
can you be more accurate? which tab do you mean? the button on the main toolbar?

**Comment by vpapanik** [comment]
Try to uninstall GiD and the interface, delete any remaining files and folders and re-install both again. Usually works fine that way.
