### ISSUE TITLE
Analysis could not run

### ISSUE THREAD

**Issue by dyiskok** [rclab-auth/gidopensees#105]
Dear gid opensees interface team,

when I perform analysis, I encounter a problem, saying that: could not run the analysis, please check generated tcl file.
but my tcl file could run the analysis and get the correct results.here are the WARNINGS:
WARNING invalid nodeId: C:/Tcl/lib/tcl8.5/reg1.2/tclreg12.dll - load nodeId 1 forces
WARNING invalid nodeId: C:/Tcl/lib/tcl8.5/reg1.2/tclreg12.dll - load nodeId 1 forces
would you please help me to checking those WARNINGS?
thanks.

**Comment by vpapanik** [comment]
These warnings come from OpenSees and they are considered a bug, they doesn't matter at all. They are deleted from the final .log file.

**Comment by 1okiii** [comment]
hello,I'm having the same issue, did you solve it? Does this error affect the calculation result?

**Comment by dyiskok** [comment]
您好，您的邮件我已经收到，谢谢！
