### ISSUE TITLE
Checking Mesh Compatibility Problem

### ISSUE THREAD

**Issue by kunekainen** [rclab-auth/gidopensees#107]
I have an SSI model which has 8000 pieces (1mx1m) volume elements. When I want to create tcl file GID normally wants to mesh the model. Because of I have too many elements in my model "Checking Mesh Compatibility" takes forever to complete.

Any suggestions? I wanted to use bigger elements and let the GID do the meshing but since it is an SSI problem I have to define many constraints, zero elements etc... So meshing in GID is not an option for me.

I appreciate any help. Thanks in advance.

**Comment by vpapanik** [comment]
There will be new option for mass ZL assignments in the new version.
