### ISSUE TITLE
GiD+OpenSees v2.7.0 Installation Issues - PLEASE READ !

### ISSUE THREAD

**Issue by cvdr888** [rclab-auth/gidopensees#111]
Hello,

I'm installing all the new versions of Opensees, Gid and GidOpensees. When I try to run the model, I get the message 'Analysis crashed'.
Aditionally, I can't import tcl data.
Can I have your help, please?
Thanks,
CR.

**Comment by cvdr888** [comment]
BTW, I just saw the last issues' replies, asking for a model. I just created the most simple example to test all this new versions. 
Here it is:

![error](https://user-images.githubusercontent.com/44230404/72454046-0c69ec80-37b8-11ea-877f-671c510f1dbc.png)

**Comment by vpapanik** [comment]
Asking for a model, not a screenshot

**Comment by cvdr888** [comment]
Here's de model and, meanwhile, I also tested with one of your v2.7.0 examples (Example B2 - Plane Frame on Elastic Soil - Dynamic Analysis.gid), obtaining the same error. 
[Test_novaversao.gid.zip](https://github.com/rclab-auth/gidopensees/files/4066817/Test_novaversao.gid.zip)

**Comment by cvdr888** [comment]
versions:
   - GID v14.0.3
   - OpenSees v3.1
   - Gid OpenSees v2.7.0

**Comment by vpapanik** [comment]
Your model runs perfectly fine with me (OpenSees v3.1.0)

Check your OpenSees installation. The .tcl file should run with OpenSees without the interface. Probably you didn't install ActiveTCL 8.6.

**Comment by vpapanik** [comment]
It is written in the known issues, and facebook

**Comment by cvdr888** [comment]
Yes, I've installed TCL8.6. 
Where do you placed your ActiveTCL folder? 
I have mine at C:\OpenSees3.1.0-x64.exe\lib\ActiveTcl, because differently from the previous versions, where OpenSees and Tcl were installed independently (and you choose the path), this new OpenSees3.1 already has the 'lib' folder.

**Comment by vpapanik** [comment]
It's already written in the known issues.
Install 8.6 as previously.
Delete all crap from OpenSees folder, leave only the executable.

**Comment by cvdr888** [comment]
Uff, done!!
I wasn't deleting the lib folder, that was why. 

Thank you sooooo much! Success!!

**Comment by vpapanik** [comment]
Of course, it was reading that lib folder by default, not the real ActiveTCL.
That was a very bad move from the OpenSees developers.

**Comment by vpapanik** [comment]
The GiD+OpenSees interface needs more tcl commands than the OpenSees executable, so that fraction of the tcl framework included in that lib folder was not sufficient.

**Comment by Al-Haaj** [comment]
That what I was complaining of thanks a lot @vpapanik for your efforts and cooperation

**Comment by zgz115** [comment]
@vpapanik Recently I got the same error:'Analysis has crashed'.I had installed all the new versions of Opensees, Gid and GidOpensees,but the tcl software version I installed is the ActiveTcl8.6.0.0b7.295590-win32-x86_64-threaded in default folder.And I saw the answer you gave to @cvdr888 ,I tried my best to solve this problem but I failed,please help me.Thank you!Here is my model!
[frame.gid.zip](https://github.com/rclab-auth/gidopensees/files/4129036/frame.gid.zip)

**Comment by vpapanik** [comment]
@zgz115 your model runs perfectly.
Have you deleted the lib folder taken from OpenSees package ? If you don't, the system does not 'look' into your ActiveTCL installation but rather reads the limited lib files.

**Comment by cvdr888** [comment]
Hello @zgz115, 
If @vpapanik wouldn't mind, i'll post the exact procedure i've adopted, just like a recipe:
1 - uninstall all
2 - install TCL 8.6 in C:\
3 - install OpenSees in C:\
4 - delete all contents from OpenSees folder, except the executable file 
5 - check if OpenSees is running (meaning that TCL is being recognized)
6 - install GidOpenSees v14.0.3 in Program File, identifying the path to OpenSees executable (in C:\OpenSees)

Good luck. It worked very well with me and my colleagues from the department. 
Best, 
CR.

**Comment by vpapanik** [comment]
Thanks a lot @cvdr888 !
I will copy your recipe in a new issue and pin it.

**Comment by zgz115** [comment]
@vpapanik I copyed "OpenSees.exe" and "tcl86t.dll"to the folder of TCLeditor,is that right?there is no lib floder.
![11](https://user-images.githubusercontent.com/60423993/73375026-264a1a00-42f6-11ea-8638-b53aa706dc48.jpg)
![22](https://user-images.githubusercontent.com/60423993/73375029-26e2b080-42f6-11ea-8508-201a450b6bc8.jpg)
![33](https://user-images.githubusercontent.com/60423993/73375030-277b4700-42f6-11ea-9816-25a818518018.jpg)

**Comment by vpapanik** [comment]
I don't know what is this TCLeditor. The .dll is not needed. Please read the updated instructions.

**Comment by zgz115** [comment]
@cvdr888 If I delete all contents from OpenSees folder, except the executable file,an error will occur.
![44](https://user-images.githubusercontent.com/60423993/73375858-6958bd00-42f7-11ea-8f59-546d7e61577a.jpg)

**Comment by vpapanik** [comment]
It's a conflict. Please delete and uninstall everything first. Go to the instructions step by step.

**Comment by vpapanik** [comment]
You are just trying to run it from inside the .zip ? Please follow the instructions.

**Comment by zgz115** [comment]
@vpapanik There is another question in records,When I open a dat file or display record,then an error occured.But it is correct for PEER format.
![1](https://user-images.githubusercontent.com/60423993/73376466-73c78680-42f8-11ea-9888-3e44ced4712f.jpg)
![2](https://user-images.githubusercontent.com/60423993/73376484-7b872b00-42f8-11ea-9175-a19356d42e8f.jpg)
![3](https://user-images.githubusercontent.com/60423993/73376488-7cb85800-42f8-11ea-9279-93feb54c52ba.jpg)
