### ISSUE TITLE
Warning: Invalid rigid diaphragm assignment has been omitted

### ISSUE THREAD

**Issue by ritamgc** [rclab-auth/gidopensees#112]
Hello, 
I have downloaded the version 2.7.0 of Gid+OpenSees and when I try to run my model, the following message appears:

 Warning: Invalid rigid diaphragm assignment has been omitted.

Could you help me? Here's my model:
[Model 1366 - Infilled.gid.zip](https://github.com/rclab-auth/gidopensees/files/4071732/Model.1366.-.Infilled.gid.zip)

**Comment by vpapanik** [comment]
I confirm the error message. Will check it out.

**Comment by theokart** [comment]
@ritamgc This truss model contains nodes with 3 dof (ux,uy,uz). Diaphragm would make sense if nodes had 6 dofs (beams). What you want to define is just infinite axial stiffness, which can be simulated through equal constraints, or (the old way ) defining big values for Area of Cross Section for truss elements ( e.g. specifying a big modification factor for cross section Area ).

**Comment by ritamgc** [comment]
@theokart thanks for your answer. I have replaced the rigid diaphragm with equal constraints. But the analysis is still not running (this time without a warning message). Could you help me again?

[Model 1366 - Infilled2.gid.zip](https://github.com/rclab-auth/gidopensees/files/4096218/Model.1366.-.Infilled2.gid.zip)

**Comment by vpapanik** [comment]
There are common nodes on different domains @theokart

**Comment by ritamgc** [comment]
@vpapanik I have noticed that problem but what am I doing wrong to have that problem?
