### ISSUE TITLE
Could not import the model geometry 

### ISSUE THREAD

**Issue by Al-Haaj** [rclab-auth/gidopensees#113]
Hello, Dear team members 
I'm trying to import model inputs from Tcl script using the new version but I got an error (Could not import the model geometry) 
I attached two simple examples. hope you find a solution and thanks.

[Test examples.zip](https://github.com/rclab-auth/gidopensees/files/4077670/Test.examples.zip)

**Comment by vpapanik** [comment]
I confirm that those models cannot be imported. We will check it out.

**Comment by vpapanik** [comment]
I strongly suspect the US units on these.

**Comment by Al-Haaj** [comment]
Thank you. I will try to modify the units

**Comment by vpapanik** [comment]
@Al-Haaj please report

**Comment by vpapanik** [comment]
Any news ?

**Comment by theokart** [comment]
@Al-Haaj  
1) Truss command is not supportet in import yet. i will add it soon.
2) try using forceBeamColumn instead of nonlinearBeamColumn, i will add it too.
3) remove comments from commands that use curly brackers "{"

Try these changes.
