### ISSUE TITLE
error: invalid command name "model"

### ISSUE THREAD

**Issue by begumemte** [rclab-auth/gidopensees#114]
After installing the latest version of GiD+OpenSees (version 2.7.0) (with GiD v14.0.3 and OpenSees v3.1), whenever I try to run an analysis I am getting the error: invalid command name "model". I think GiD is not able to read the TCL files because before getting the error, a message appears as "generate .tcl file". The previous versions automatically generated TCL files on running the analyses. Even if I generate the TCL file separately before running the analysis, it does not help. Also, the error mentioned above does not occur if the analysis is run in OpenSees manually which signifies that there is no mistake in the TCL files.
Kindly look into the matter ASAP.
Thank You.

**Comment by vpapanik** [comment]
Please attach your model to check it out. You probably used the GiD menu for executing the analysis instead of the GiD+OpenSees menu.

**Comment by kamalshr** [comment]
i am facing same issue.Please help me .Thank you

**Comment by vpapanik** [comment]
read above

**Comment by kamalshr** [comment]
Thanks for reply....it was compatibility issue between opensees abd Gid+opensees.
