### ISSUE TITLE
READ THIS FIRST ! Proper installation of GiD+OpenSees v2.8.5

### ISSUE THREAD

**Issue by vpapanik** [rclab-auth/gidopensees#115]
1. **Delete/uninstall** all previous versions of OpenSees and ActiveTcl.
2. Download the latest **ActiveTcl** from _https://downloads.activestate.com/_ and install it in the default folder (C:\ActiveTcl). Make sure that the option 'Add to PATH' is checked.
3. Download and **open** _OpenSees3.2.1-x64.exe.zip_. **Extract** OpenSees.exe from _/bin_ folder to _C:\OpenSees_. Do not extract any other file !
4. Check if OpenSees is running on the command line.
5. Download and install the latest **stable** version of GiD from _https://www.gidhome.com/download_ in default directory.
6. Download and install the GiD+OpenSees Interface v2.8.5 setting the OpenSees path to _C:\OpenSees_.

*Note : For the moment OpenSees.exe v3.2.2 and v3.3.0 cannot find the ActiveTcl installation. Please use OpenSees 3.2.1 from :*

**https://www.dropbox.com/sh/uau7mcb8zuwk2fc/AABcQxlVv0fNb5Imw2kZmvN1a?dl=0**

**Comment by Yaoure** [comment]
![image](https://user-images.githubusercontent.com/61788176/76551032-fa8c8900-648a-11ea-8dbb-5669fb66f117.png)

My screen comes like this when i install it, any help

**Comment by sepugua** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/61788176/76551032-fa8c8900-648a-11ea-8dbb-5669fb66f117.png)
> 
> My screen comes like this when i install it, any help

You can use the option Repair Gid (Gid folder) and mark reset preferences.

**Comment by KezhSardasht** [comment]
> ![image](https://user-images.githubusercontent.com/61788176/76551032-fa8c8900-648a-11ea-8dbb-5669fb66f117.png)
> 
> My screen comes like this when i install it, any help
Hi,
I had the same problem and I used the following steps...
1. Go to C:\Users\''Computer Name''\AppData\Roaming\GiD 
2. Remove all the files inside GiD folder
3. Open GiD again and you will see your Full-Screen Mode is removed.

**Comment by zrunming** [comment]
Unzip all files

**Comment by DonaldDUT** [comment]
hi professor, i can't find the ndmaterial-PlaneStressUserMaterial and PlateFromPlaneStress when i was building a model. but there is a warning: PlaneStressUserMaterial already exists in data base as shown in the picture. where can i find it and use it 
![image](https://user-images.githubusercontent.com/57903367/89868654-c22dda00-dbe5-11ea-881d-09d1614c5694.png)
![2`ZL W~%8$Y  @`1JMXUC$VH6](https://user-images.githubusercontent.com/57903367/89868725-dd004e80-dbe5-11ea-8980-816d49fe5428.png)
@vpapanik

**Comment by rafmuvdi** [comment]
I have not been able to install the app.
When Checking  if OpenSees is running on the command line, this comes up....(see attach)
<img width="607" alt="Anotación 2020-09-11 082059" src="https://user-images.githubusercontent.com/71135470/92930934-5c14bc80-f408-11ea-9fde-0e1c66539fb1.png">
.

**Comment by rafmuvdi** [comment]
Pls Help

**Comment by zahrahemmati** [comment]
Hi, I'm going to model Example 8 on the opensess site with gid. But after opening the tcl file with gid, I encounter these errors. And I can not. I can analyze it, please guide me
![Untitled](https://user-images.githubusercontent.com/75049026/100292364-83a20c80-2f95-11eb-9a75-63de7d61ebff.jpg)
![Untitled123](https://user-images.githubusercontent.com/75049026/100292369-86046680-2f95-11eb-810c-bbe7b76bcb15.jpg)
![Untitled1234](https://user-images.githubusercontent.com/75049026/100292385-8997ed80-2f95-11eb-95c0-cd5e80df4c87.jpg)

**Comment by vpapanik** [comment]
This issue is no longer important.
All-in-one installation in v2.9.0.

**Comment by nasimre** [comment]
Hi Professor, I wanted to ask you whether it is possible to link GiD with openseesPy? Since I use python to analyze geotechnical modeling, it is important to me to connect GiD with openseespy.
thank you
