### ISSUE TITLE
When I open a dat file or display record, then an error occured

### ISSUE THREAD

**Issue by vpapanik** [rclab-auth/gidopensees#116]
@vpapanik There is another question in records,When I open a dat file or display record,then an error occured.But it is correct for PEER format.
![1](https://user-images.githubusercontent.com/60423993/73376466-73c78680-42f8-11ea-9888-3e44ced4712f.jpg)
![2](https://user-images.githubusercontent.com/60423993/73376484-7b872b00-42f8-11ea-9175-a19356d42e8f.jpg)
![3](https://user-images.githubusercontent.com/60423993/73376488-7cb85800-42f8-11ea-9279-93feb54c52ba.jpg)

_Originally posted by @zgz115 in https://github.com/rclab-auth/gidopensees/issues/111#issuecomment-579845058_

**Comment by vpapanik** [comment]
Can't read Chinese. Better post your model to check.

**Comment by zgz115** [comment]
Thank you very much!This is the model.
[frame.gid.zip](https://github.com/rclab-auth/gidopensees/files/4129256/frame.gid.zip)

**Comment by vpapanik** [comment]
1. There is no viewer association with .dat files in your computer. Either rename it to .txt (opens with Notepad) or associate and editor with .dat files.
2. Replace commas with spaces or tabs. Will correct that in order to recognize commas as well.

**Comment by zgz115** [comment]
@vpapanik The problem is solved, thank you very much!

**Comment by vpapanik** [comment]
managed to install correctly ?

**Comment by zgz115** [comment]
@vpapanik no,again analysis is crashed,I installed it according to the steps you said, I don't know why it is still wrong?tcl86t.dll is needed,otherwise opensees is not running.

**Comment by vpapanik** [comment]
Have you checked 'Add to PATH' when installed ActiveTCL ? If not, do it again. And restart your system.

**Comment by zgz115** [comment]
@vpapanik Thank you very much for your attention.I have checked it,I think it is right(as follow picture). restart system is not working.In addition, the latest version of active tcl cannot be installed, error as follow.I do not know why?
![1](https://user-images.githubusercontent.com/60423993/73421260-2e3ea400-4360-11ea-9923-0a25b2479fd7.jpg)
![2](https://user-images.githubusercontent.com/60423993/73421266-33035800-4360-11ea-9a81-2bc23f36f4e8.jpg)

**Comment by zgz115** [comment]
@vpapanik  I have resolved the "GID have crashed" issue by installing opensees version 2.5.0

**Comment by zgz115** [comment]
@vpapanik Why can't these numbers be modified?I have clicked the update changes button.
![图片2](https://user-images.githubusercontent.com/60423993/74602048-b69ea200-50df-11ea-9fce-a9b37be747bd.jpg)
