### ISSUE TITLE
where is my wrong?

### ISSUE THREAD

**Issue by mcullu** [rclab-auth/gidopensees#117]
**### H-Pile compressive test, but it isnt give section results**

# SET UP ----------------------------------------------------------------------------
wipe;								# clear memory of all past model definitions
model BasicBuilder -ndm 2 -ndf 3;	# Define the model builder, ndm=#dimension, ndf=#dofs
set dataDir Data;					# set up name of data directory -- simple
file mkdir $dataDir; 				# create data directory

# define UNITS ----------------------------------------------------------------------------
set in 1.; 						# define basic units -- output units
set kip 1.; 					# define basic units -- output units
set sec 1.; 					# define basic units -- output units
set LunitTXT "inch";			# define basic-unit text for output
set FunitTXT "kip";				# define basic-unit text for output
set TunitTXT "sec";				# define basic-unit text for output
set ft [expr 12.*$in]; 			# define engineering units
set ksi [expr $kip/pow($in,2)];
set psi [expr $ksi/1000.];
set lbf [expr $psi*$in*$in];		# pounds force
set pcf [expr $lbf/pow($ft,3)];		# pounds per cubic foot
set psf [expr $lbf/pow($ft,3)];		# pounds per square foot
set in2 [expr $in*$in]; 			# inch^2
set in4 [expr $in*$in*$in*$in]; 	# inch^4
set cm [expr $in/2.54];				# centimeter, needed for displacement input in MultipleSupport excitation
set PI [expr 2*asin(1.0)]; 			# define constants
set g [expr 32.2*$ft/pow($sec,2)]; 	# gravitational acceleration
set Ubig 1.e10; 					# a really large number
set Usmall [expr 1/$Ubig]; 			# a really small number

# Structural-Steel H-section properties -------------------------------------------------------------------

# set HSec HP10x42

# from Steel Manuals:
# in × lb/ft 	Area (in2) 	d (in) 	bf (in) 	tf (in) 	tw (in) 	Ixx (in4) 	Iyy (in4)
# HP10x42  	    12.4 		9.70 	10.075 	   0.42 	    0.415 	    210 	    71.7
set d [expr 9.70*$in];	 # nominal depth
set tw [expr 0.415*$in];	 # web thickness
set bf [expr 10.075*$in]; # flange width
set tf [expr 0.42*$in];	 # flange thickness
set A [expr 12.4*$in2];		#Area (cm2)
set Ix [expr 210*$in4];
set Iy [expr 71.7*$in4];
set J [expr 0.813*$in4];
set G [expr 11200*$ksi];
set nfdw 16;	# number of fibers along web depth 
set nftw 4;		# number of fibers along web thickness
set nfbf 16;	# number of fibers along flange width (you want this many in a bi-directional loading)
set nftf 4;		# number of fibers along flange thickness

# set dw [expr $d-2*$tf];
# set y1 -12.32; #[expr -$d/2];
# set y2 -11.25; #[expr -$dw/2];
# set y3 11.25; #[expr $dw/2];
# set y4 12.32; #[expr $d/2];
  
set dw [expr $d-2*$tf];
set y1 [expr -$d/2];
set y2 [expr -$dw/2];
set y3 [expr $dw/2];
set y4 [expr $d/2];  
  
set z1 [expr -$bf/2];
set z2 [expr -$tw/2];
set z3 [expr $tw/2];
set z4 [expr $bf/2];
  
 
# MATERIAL parameters -------------------------------------------------------------------
# define MATERIAL properties ----------------------------------------
set LCol [expr 10*12$in]; 		# H pile length
set Fy [expr 60.0*$ksi];
set Es [expr 29000*$ksi];			# Steel Young's Modulus
set nu 0.3;
set Gs [expr $Es/2./[expr 1+$nu]];  # Torsional stiffness Modulus
set Hiso 0;
set Hkin 1000;

set Weight [expr 3000.*$kip]; # superstructure weight
set Mass [expr $Weight/$g]

# set matIDhard 1;
set SecID 1;
set matID 1;
# uniaxialMaterial Steel01 $matTag $Fy $E0 $b
# uniaxialMaterial Hardening  $matIDhard $Es $Fy   $Hiso  $Hkin

  # section fiberSec  $SecID {
     # #                     nfIJ  nfJK    yI  zI    yJ  zJ    yK  zK    yL  zL
     # patch quadr  $matIDhard $nfbf $nftf   $y1 $z4   $y1 $z1   $y2 $z1   $y2 $z4
     # patch quadr  $matIDhard $nftw $nfdw   $y2 $z3   $y2 $z2   $y3 $z2   $y3 $z3
     # patch quadr  $matIDhard $nfbf $nftf   $y3 $z4   $y3 $z1   $y4 $z1   $y4 $z4
  # }

uniaxialMaterial Elastic $matID $Es
     

  section fiberSec  $SecID {
     #                     nfIJ  nfJK    yI  zI    yJ  zJ    yK  zK    yL  zL
     patch quadr  $matID $nfbf $nftf   $y1 $z4   $y1 $z1   $y2 $z1   $y2 $z4
     patch quadr  $matID $nftw $nfdw   $y2 $z3   $y2 $z2   $y3 $z2   $y3 $z3
     patch quadr  $matID $nfbf $nftf   $y3 $z4   $y3 $z1   $y4 $z1   $y4 $z4
  }

#define GEOMETRY-------------------------------

     #Nodal coordinates:
node 1 0 0 0;
node 2 $LCol 0 0 ;

#single point constrains -- Boundary conditions
fix 1 1 1 1;
fix 2 0 0 0;

# # #nodal masses:
# mass 1 $Mass 0 0;		#node#, Mx My Mz, Mass =weight /g
mass 2 $Mass 0 0;

#Results
recorder Element -file Element1.out -time -ele 1 globalForce
recorder Element -file ele1global.out -time -ele 1 localForce
recorder Element -file ele1sec1Defo.out –time -ele 1 section 1 deformation 
recorder Element -file ele1sec1StressStrain.out –time -ele 1 section 1 fiber $y2 $z2 $matID stressStrain
# recorder Element -file ele1sec1StressStrain.out –time -ele 1 section 1 fiber $y3 $z1 $matIDhard stressStrain
recorder Element -file ele1sec1Force.out –time -ele 1 section 1 force

#define ELEMENTS-------------------------------------

geomTransf Linear 1;			#associate a tag to transformation

#connectivity: (make A very large, 10e6 times its actual value)
element elasticBeamColumn 1 1 2 $A $Es $Iy 1;	#element elasticBeamCloumn $eletag $inode $jnode $A $E $Iz $transfTag

#define GRAVITY----------------------------------------
pattern Plain 1 Linear {
eleLoad -ele 1 -type -beamUniform -7.94; 	#distributed superstructure-weight on beam 

}

#set AXIAL LOAD --------------------------------------------------------
pattern Plain 2 Linear {
set P [expr -1000.*$kip];	# + Tension, - Compression

load 2 $P $LCol 0; 
}

constraints Plain;
numberer Plain;
system BandGeneral;
test NormDispIncr 1.0e-8 100;
algorithm Newton;
numberer RCM;

integrator LoadControl 0.1;
#analyze $numIncr <$dt> <$dtMin $dtMax $Jd>

analysis Static;
analyze 100;
loadConst -time 0.0;

puts done!

**Comment by vpapanik** [comment]
this should be posted to the OpenSees forum, it is not about the interface.
