### ISSUE TITLE
unable to import the standard brick elements from tcl file

### ISSUE THREAD

**Issue by Bhag821351** [rclab-auth/gidopensees#119]
Hi,

I am trying to import the model from the existing tcl file, beam-column elements are getting imported but the standard brick elements are not getting imported. I can send the tcl file if needed.

Thank you
N. Bhagya sree

**Comment by vpapanik** [comment]
Yes, please do

**Comment by Bhag821351** [comment]
[New Text Document.txt](https://github.com/rclab-auth/gidopensees/files/4248805/New.Text.Document.txt)

**Comment by Bhag821351** [comment]
Is it because of any  mistake in my tcl file or is it problem with interface? I need the interface to read the geometry part (excluding analysis) atleast  from my existing tcl file. Please help me in this regard

**Comment by vpapanik** [comment]
The import works fine in v2.7.0 

![image](https://user-images.githubusercontent.com/22118061/78036189-afbbae00-7372-11ea-821d-7cd7a2d8ebf4.png)

**Comment by vpapanik** [comment]
Will be fixed in the next version of the importer.
