### ISSUE TITLE
Error encountered while importing tcl file 

### ISSUE THREAD

**Issue by Bhag821351** [rclab-auth/gidopensees#120]
When I  tried import the Tcl script I am facing the error dialog box which shows Invalid command name GiD_UNITS, errror message is as below. I think there is no problem with Tcl file as it was created by the Interface.
![image](https://user-images.githubusercontent.com/52022040/75859189-90873a80-5e1f-11ea-8413-439170bfb57e.png)

**Comment by vpapanik** [comment]
Please send the tcl script in order to test it.

**Comment by vpapanik** [comment]
Script not sent, issue closed.
