### ISSUE TITLE
element without material (no spacing in material name!)

### ISSUE THREAD

**Issue by mircem** [rclab-auth/gidopensees#122]
Hi,

I keep getting the same error when using volume elements. I understand that a similar issue has been posted and resolved, and that the solution to that problem lied in naming the material without spacing. In this case however, I have named my material correctly (apparently), but I still get the same message. I have tried with several different models, but keep getting the same message.

I have attached a very simple model that illustrates the problem and the corresponding error message. I am using versions 14.0.3 and v2.7.0. 

BR, Miran

[example1.gid.zip](https://github.com/rclab-auth/gidopensees/files/4377252/example1.gid.zip)

![error_message](https://user-images.githubusercontent.com/62619589/77468461-d9725380-6e0d-11ea-8127-d793111e7b74.JPG)

**Comment by vpapanik** [comment]
It works on my computer. Try deleting all automatically created groups, transform your model again and retry. Please report back.

**Comment by mircem** [comment]
Thank you for the reply. What is meant by "automatically created groups", and is there a simple way to delete these groups?  I have tried to delete all solid elements and nDmaterials that are not in use. I still get the same error. 

I have attached the tcl.-file that gets generated when I get the error.. As you can see, the error appears immediately so that no code is written (only the initial, descriptive text).

I am using OpenSees3.2.0, but the installation file for GiD+OpenSees states that OpenSees3.1.0 should be used. Could this be the reason? 

[example1.zip](https://github.com/rclab-auth/gidopensees/files/4381984/example1.zip)

**Comment by theokart** [comment]
Hello Miran,
I think the problem is that you have created a node ( assigned a force to ) which is not connected to any geometry entity.
Check the attached model and its geometry (Geometry>view geometry)
[example1.gid.zip](https://github.com/rclab-auth/gidopensees/files/4383275/example1.gid.zip)

**Comment by mircem** [comment]
Thank you so much for the feedback, Theocharis. When I run the model you have posted, it works fine. However, if I create the same model, I get the same error. I have no problem with beam or truss elements, only solids. 

I have checked the manual and the tutorials to see if I am doing something wrong, but everything seems fine. I have tried the following;
 - Re-installed OpenSees, ActiveTcl, GiD and GiD+OpenSees, OpenSees alone works fine.
 - Several different models with different materials
 - Model with only nodal loads
 - Model with only surface loads
 - Model with only volume loads
 - Collapsed model before mesh (Geometry - Edit - Collapse - Model)
 - Collapsed mesh (Mesh - Edit Mesh - Collapse - Mesh)

I have attached a new model with a nice, simple mesh (volume loads as body forces on soilbrick). 

 - I am using OpenSees3.2.0, but the installation file for GiD+OpenSees states that OpenSees3.1.0 
   should be used. Could this be the reason?
- Is there anything particular with regards to the settings I need to  be aware about? I have been 
  using primarily default settings.

[example6.gid.zip](https://github.com/rclab-auth/gidopensees/files/4387473/example6.gid.zip)

**Comment by theokart** [comment]
@mircem here is the problem :
After any change on the geometry you should generate mesh again. Actually you have a mesh that does not correspond to geometry you have ( which is correct now ).
At the model you attached, if you Generate mesh through the corresponding button on the toolbar, you will see that it will work fine.

**Comment by mircem** [comment]
Thank you for you patience, but hope you can bear with me just a little more.

I always re-mesh when changing the geometry and/or conditions, and I have done so here. I have scavenged the manual, tutorials, issues and videos in order find what I am missing, but everything seems fine. However, I am clearly doing something wrong. 

Starting from the model in the previous post (the one with correct geometry), you can see exactly what I am doing step-by-step in the attached file with screenshots. They are named in the correct step-order.

I apologize in advance if the issue is something trivial, but for me this seems very strange.

[step_by_step.zip](https://github.com/rclab-auth/gidopensees/files/4392677/step_by_step.zip)
 
Best regards, Miran

**Comment by theokart** [comment]
@mircem, 
Well, this is really weird. I think this is GiD's bug. At least now i think we found the real problem.

What i do different is that i do not change element size (because it just does not matter, as you have defined it before) at **image 29** as well as i do not enable the checkbox "Get meshing parameters from model".

I think the bug is on this checkbox. 
Do exactly the same steps two times, with this option checked and unchecked respectively.

You will see the difference at **image 30**. You would expect only hexahedra elements. But if you check this option, for some weird reason, GiD produces linear and quad elements too, for which of course you have not defined an OpenSees element type. This is the reason of the error message.

I hope i helped.

**Comment by mircem** [comment]
@theokart, thank you, it finally worked! As I am new to GiD, I didn't pick up on the fact that quads where somehow created.
