### ISSUE TITLE
Tutorial 5 – Site Response Analysis of a Layered Soil Column

### ISSUE THREAD

**Issue by cysorianoc** [rclab-auth/gidopensees#125]
Dear sirs I would like to know if is it possible to have access to the .gid file of the Tutorial example 5 related to the site response of a layered soil column. I have tried to follow the steps, however my model seems not to be working. Therefore I would like to compare my settings with the original one and detect the possible issues (I am also a bit confused with the definition of the Lysmer-Kuhlemeyer  dashpot and how to define the equal constraints ). 

 At first I tried to run some of the other tutorial examples and all of them work. Therefore, is not an installation issue. 

I am also attaching my model.

Best regards and thank you.
 

[soilcolumn1.gid.zip](https://github.com/rclab-auth/gidopensees/files/4507896/soilcolumn1.gid.zip)

**Comment by vpapanik** [comment]
There's something missing here... there is a master equaldof there without a slave, can you check ?

![image](https://user-images.githubusercontent.com/22118061/79989039-10dd2a00-84b8-11ea-95cc-d0650457e589.png)

@theokart what do you think ?

**Comment by cysorianoc** [comment]
Dear sirs, I updated the model. I thing I managed to create the zero length element for the dashpot using the layers, in my model were defined as nodes 302 and 304 (turning on and off the layers). 

I also applied the equal constraints by defining as master node the bottom node of the soil column (node 303) and as slave node 304 (one of the nodes from the zero lenght elements of the dashpot). The TCL file shows the followwing definition:

# Equal Constraint/equalDOF Definition : equalDOF $MasterNode $SlaveNode $DOFs

equalDOF    302    303   2 3 ; # ID : 1


See attached the updated model.

I would appreciate a lot if the .gid file of this example solved  is available, it would help me clarify my doubts.

Again, thank you for the attention.

[soilcolumn1.gid.zip](https://github.com/rclab-auth/gidopensees/files/4518134/soilcolumn1.gid.zip)
