### ISSUE TITLE
Modelling shallow foundations and structure

### ISSUE THREAD

**Issue by mvics** [rclab-auth/gidopensees#126]
Hello! I'm new to GID+OpenSees but I have been using opensees for 8 months. I have decided to start using this interface to study soil structure interaction problems. I have modelled a simple one-bay frame in 3D. I used the Displacement-Based Beam-Column and the section fiber to model the frames and Concrete04 and Steel02 materiales. I added the rigid diaphragm and fixed the base of columns. I performed a pushover analysis (interval 2) after the gravitational loads application (interval 1). The results were okey. 

Once the structure model was proved to work properly, I added the shallow foundations as volumes. I used standard brick element to model them and an elasticisotropic concrete material. I did the mesh and activaded automatic EqualDOF between nodes of different domains option. The base of the foundations is fixed. The analysis doesnt run correctly since the model is not moving, not even in the gravitational loads step (in which only the frames should be deformed). I applied the equal constrain master/slave nodes to each column base node and their corresponding 4 nodes of the foundation. 

I do not know which might be the problem. Maybe something related to the degrees of freedom definition or the connection between solid and beam elements. I decided to start working on this simple model but my next step will be adding the soil.

Thank you.  

PS: I tried to import the .tcl created by GID in a new opensees problem type file and a message error appeared. I have checked that there have been some problems related to this bug. The versions I am using are: Opensees: 2.5.5. GID: 14.0.2 GID+OpenSees: 2.7.0

[prueba5.gid.zip](https://github.com/rclab-auth/gidopensees/files/4515580/prueba5.gid.zip)

**Comment by mvics** [comment]
Hi again. I have also checked that some aspects previosly defined in the superstructure model dissapear in the .tcl file that includes the foundations volumes... For instance, the materials of the structure, the rigid diapraghm definition... I tried to include the foundations in a different layer but then the analysis crashed...

**Comment by vpapanik** [comment]
You can check again in a few days when we release v2.8.0
