### ISSUE TITLE
Displacement control analysis

### ISSUE THREAD

**Issue by kamalshr** [rclab-auth/gidopensees#127]
I am performing displacement control pushover analysis of a cantilever column. But after applying displacement in X direction,  i am not getting any reaction force in x direction and force reaction in y direction is very high. Some input data and output result attached below.

Please help me Thank you

![Screenshot (2)](https://user-images.githubusercontent.com/63670352/80813507-c5c5c400-8be7-11ea-98df-f3fb44ce5b9f.png)
![Screenshot (3)](https://user-images.githubusercontent.com/63670352/80813523-ca8a7800-8be7-11ea-8164-f7129c89888b.png)
![Screenshot (4)](https://user-images.githubusercontent.com/63670352/80813532-ce1dff00-8be7-11ea-950d-bbb40574b38c.png)
![Screenshot (7)](https://user-images.githubusercontent.com/63670352/80813544-d1b18600-8be7-11ea-82a6-f2370591c6b3.png)
![Screenshot (8)](https://user-images.githubusercontent.com/63670352/80813550-d5450d00-8be7-11ea-9416-f2c5c9a6531c.png)
![Screenshot (9)](https://user-images.githubusercontent.com/63670352/80813557-d8d89400-8be7-11ea-8a56-f6025ee3d57d.png)

**Comment by vpapanik** [comment]
Where are you measuring the reaction force ? at the base ? please attach your model (zip file with the whole .gid folder)

**Comment by kamalshr** [comment]
@vpapanik thanks for your reply. Yes,  i measure reaction force at the base of column. Complete model folder is attached below. Please find it.

Thank you

[pier.zip](https://github.com/rclab-auth/gidopensees/files/4576361/pier.zip)

**Comment by vpapanik** [comment]
It seems that you didn't include any loading on the second interval. Check the .tcl file, there's nothing there.
