### ISSUE TITLE
Problem about create .tcl

### ISSUE THREAD

**Issue by luckypants95** [rclab-auth/gidopensees#128]
Dear sir：

Hello, I have problem about create .tcl. 
The problem is when I create .tcl, the tcl file couldn't complete and interrupt.
But I could successfully create .tcl before. How could I solve the problem?
Any advices and helps that you give are highly appreciated.
![tcl incomplete](https://user-images.githubusercontent.com/66583400/83993381-d48d5c80-a985-11ea-8690-26d3897e1039.jpg)

**Comment by vpapanik** [comment]
We will release v2.8.0 in a few days
