### ISSUE TITLE
 GID+Opensees crashes

### ISSUE THREAD

**Issue by fosiano** [rclab-auth/gidopensees#129]
Dear gid opensees interface team,
when I select a command like “Create .tcl only” on GID+Opensees menu, GID crashes every time I play the command and for every model I want to investigate, selected from the example file I had just downloaded from https://github.com/rclab-auth/gidopensees/wiki.
Consider that, just some weeks ago, everything was working fine. (maybe some windows update causes the trouble?).
The Windows Event Viewer shows this log (sorry for my system in Italian):
“Nome dell'applicazione che ha generato l'errore: gid.exe, versione: 14.0.0.0, timestamp: 0x5e66a9e4
Nome del modulo che ha generato l'errore: ntdll.dll, versione: 10.0.18362.815, timestamp: 0xb29ecf52
Codice eccezione: 0xc0000374
Offset errore 0x00000000000f9229
ID processo che ha generato l'errore: 0x23b8
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d6504b2e2c20f7
Percorso dell'applicazione che ha generato l'errore: C:\Program Files\GiD\GiD 14.0.4\gid.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\SYSTEM32\ntdll.dll
ID segnalazione: 2380bc59-72a6-45bb-bdc6-d0f6723f0593”

I work with the latest gid version 14.0.4 and interface version 2.7.0.
Do you know if any other user experienced the same issue?
any help appreciated...
thanks.

**Comment by vpapanik** [comment]
Wait for a few days until we release the next version 2.8.0

**Comment by fosiano** [comment]
Ok, thanks.
