### ISSUE TITLE
Possible to open existing tcl file?

### ISSUE THREAD

**Issue by charden74** [rclab-auth/gidopensees#13]
Hello, this is an amazing program and interface.

I am a new user to Gid, and forgive me for this is probably a very dumb question. But is it possible to read/open an existing opensees model / tcl file and run using your new interface?

Thank you very much, Best, Chad

**Comment by vpapanik** [comment]
No, I am afraid this is not possible at the moment, but we will take it into consideration for future versions. However, it will be easy to re-create your existing models in the graphical environment in order to take advantage of the interface features.

**Comment by charden74** [comment]
Thank you!
