### ISSUE TITLE
tcl version 8.6.10 not "compatible" with version 8.6.5

### ISSUE THREAD

**Issue by sismo68** [rclab-auth/gidopensees#130]
Hi.
I just tried to run one of the tutorial problems of the GiD convention (elastic truss, 2018) with GiD Opensees V2.8.0 for the first time using Opensees version 3.2.2 (latest version on 7/14/2020). When trying to run the example, the following error pops up at the Opensees screen:

"C:/Program Files/GiD/GiD 14.0.5/scripts/tcl/init.tcl: version conflict for package "Tcl": have 8.6.10, need exactly 8.6.5
version conflict for package "Tcl": have 8.6.10, need exactly 8.6.5"

After modifying the init.tcl file changing the tcl version number, GiD stopped working and had to go back to the original init.tcl but GiD Opensees does not run Opensees from the "Run Analysis and postprocess" menu.
[truss.gid.zip](https://github.com/rclab-auth/gidopensees/files/4921379/truss.gid.zip)

**Comment by sismo68** [comment]
Problem solved! reinstalled all software (tcl, opensees, GiD, and GiD Opensees) and now is working (for Opensees 3.2.1). No working for Opensees 3.2.1

**Comment by vasudeochaudhari** [comment]
I am also facing the same issue, however, after reinstallation problem still persisting. Please Help

**Comment by Kennethsq96** [comment]
simos68 could you send me version 3.2.1 of opensees? I can not find it anywhere.

**Comment by akki21686** [comment]
> Problem solved! reinstalled all software (tcl, opensees, GiD, and GiD Opensees) and now is working (for Opensees 3.2.1). No working for Opensees 3.2.1

where did you download tcl from?

**Comment by MXW1993** [comment]
@sismo68 Hello, Could you send me version 3.2.1 of opensees ? e-mail:  mengxiaowei_1993@163.com   thanks!

**Comment by rafmuvdi** [comment]
Yes, pls. THKS.
R.M.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vpapanik** [comment]
It seems that OpenSees 3.2.2 works with tcl 8.6.10. However there's no such installation at ActiveTcl !
Try using 3.2.1 for the moment.

**Comment by akki21686** [comment]
> It seems that OpenSees 3.2.2 works with tcl 8.6.10. However there's no such installation at ActiveTcl !
> Try using 3.2.1 for the moment.

How to get 3.2.1 version?

**Comment by wbellotta** [comment]
Dear  Prof. V.K. Papanikolaou,
I need your hep!
I'm still working within Opensees 2.5.0 (32-bit ) and I've just  installed GID 15..0.1 and GidOpensees  2.8.0.  It seems to me  everything is ok. Now  I find some problem when I try to import *.tcl file created by another SW ( CDSWIN 2020 ). When I try to import  it the warning below appears

![Not-import model geom](https://user-images.githubusercontent.com/32549896/97335021-a699ad80-187d-11eb-9490-1cc5343a9d1f.JPG).

I've tryed to attach the *.tcl file I need to import but  the file type isn't supported 
Can you help me, please
Thanks in advance.
walter

**Comment by wbellotta** [comment]
Dear Prof. V.K. Papanikolaou,
may be I've  found  the way to attach the  *.tcl file  below

[DatiDyn-1.zip](https://github.com/rclab-auth/gidopensees/files/5446954/DatiDyn-1.zip)

I'm waiting for your kind relpy
walter

**Comment by wbellotta** [comment]
Hi @sismo68 ,
 Could you send me  the  3.2.1 Opensees rel. and the  ActiveTcl 8.6.5 ?
 If you can  e-mail me at info@bellottaingegneria.com
I  will really appreciate your help!
 thanks!
walter
walter

**Comment by wbellotta** [comment]
Hi all, I ve met another problem  just running  the Plane Frame - Dynamic Analysis ( v.2.7.0) example in GIG+Openees SW. When I click on the Loma Prieta Display record ( see the imagin below ), the acceleration Time History graph appears like the imagine that follow below.  
![TH Loma Prieta](https://user-images.githubusercontent.com/32549896/97878002-565b9900-1d1e-11eb-8689-d392cbfbbcad.JPG)

The acceleration Time History graph appears like the imagine below.  

![Records Loma Prieta](https://user-images.githubusercontent.com/32549896/97878027-5fe50100-1d1e-11eb-94df-ea53f89ab485.JPG)

You can notice something strange appears. The  Time  duration along the X-X Axis is  near 40.000 sec ( the real one is almost 40 sec. ) and the acceleration magnitude along the Y-Y axis vary between   -4.000.000 and +4.000.000  ( the real one is near + - 0,4 g ).

 I've  controlled the GID+Opensees data units and everything seems to be ok. Where do I commit any mistake?
Any help will be appreciate.
Thanks in advance.
walter

**Comment by vpapanik** [comment]
Check your delimiter, it may be a comma instead of a dot or vice versa, depending on your computer settings.

**Comment by wbellotta** [comment]
Dear Prof.  Papanikolaou, many thanks for your kind reply. 
I'd like to ask you another question on a pending issue  about the problem that happens when I try to import *.tcl file created by another SW ( CDSWIN 2020 ). I sent your   related *.tcl  file   on 27 Oct 2020 and  you may haven't seen it so far.  I'm still waiting for your kind reply. 
walter

**Comment by VKotzamanis** [comment]
> Hi.
> I just tried to run one of the tutorial problems of the GiD convention (elastic truss, 2018) with GiD Opensees V2.8.0 for the first time using Opensees version 3.2.2 (latest version on 7/14/2020). When trying to run the example, the following error pops up at the Opensees screen:
> 
> "C:/Program Files/GiD/GiD 14.0.5/scripts/tcl/init.tcl: version conflict for package "Tcl": have 8.6.10, need exactly 8.6.5
> version conflict for package "Tcl": have 8.6.10, need exactly 8.6.5"
> 
> After modifying the init.tcl file changing the tcl version number, GiD stopped working and had to go back to the original init.tcl but GiD Opensees does not run Opensees from the "Run Analysis and postprocess" menu.
> [truss.gid.zip](https://github.com/rclab-auth/gidopensees/files/4921379/truss.gid.zip)

For everyone who is having the above problem and everyone else who is working in academia and can't afford the ActiveState solution: (WINDOWS 10)

-  Compile Tcl/Tk 8.6.10. That can be done either by:

1. Compiling the source code via MC++.
2. Download Magicsplat registry compiler (open source, liberal licensing), v.1.10.0 and installing the libraries on desktop. A folder named "Tcl8.6" should have been created.

- Download OpenSees.322.exe from the Dropbox folder Dr.Papanikolaou has provided, and set it on a directory of your choice.
- If you run OpenSees at this point you should get a message that the file init.tcl was not found in directories C:\\Users\xxx\lib 
- You can either edit Opensees to search for another directory (tcl library PATH) -OR- move the components of the Tcl8.6 folder to  C:\\Users\yourprofilename\ .
- Reinstall GiD+OpenSees285.exe and choose Opensees322.exe as the Opensees executable file.

Problems solved (google purposes):
.... TCL .... NEED EXACT 2.8.10
... INIT.TCL CANNOT BE FOUND
... This probably means that Tcl wasn't installed properly.

**Comment by vpapanik** [comment]
The issue is solved in v2.9.0 with the All-in-One installation (works with latest OpenSees 3.3.0)
