### ISSUE TITLE
Gid + Opensees crashing 

### ISSUE THREAD

**Issue by sismo68** [rclab-auth/gidopensees#131]
after a successful install following the configuration directions and running the elastic truss tutorial just fine, but when attempting to change for instance point loads at different truss nodes, and after meshing and saving the project again, when trying to create the tcl and run Opensees, Gid crashes ans shuts down. A review of the created tcl the new point loads were not written in the file,  also, before crashing GiD shows the interval (only one) as 'solved'

**Comment by DonaldDUT** [comment]
hi, i just installed the interfaceV2.8.0 with GID 14.0.1 , also working with the opensees version 3.2.2 . but always facing failure when performing the model. could you please tell me the versions of  GID+opensee, GID and Opensees you adopted,thx @sismo68

**Comment by cysorianoc** [comment]
I had the same issue, the GID immediatly creashes. It seems that GID+OpenSees v2.8.0 is compatible with OpenSees3.2.1, however on the official website of OpenSees there is only available the OpenSees3.2.2 version which is also presenting some problems finding the tcl executable. I tried to run the OpenSees3.2.2 executable file from the folder c://OpenSees and it did not work on my computer. When doing the same with a previous version (Opensees3.2.0) it worked fine. The point is that the 3.2.1 version seems missing, then I had to work again with GID+Opensees V2.6.0.

**Comment by sismo68** [comment]
That issue was resolved in my case when i followed the instructions for
unistalling and reinstalling all the software (tcl, gid and gid opensees)
in the order posted.

**Comment by DonaldDUT** [comment]
@sismo68 @cysorianoc thank you for all your discussions. as @cysorianoc mentioned, the OpenSees v3.2.1 can not be found anywhere. if possible, could you @sismo68  send me  .zip file of  OpenSees v3.2.1 to email: yctang.dlut@foxmail.com. thank u so much

**Comment by sismo68** [comment]
The installation process also worked with 3.2.2, this is the version i know
use.

**Comment by DonaldDUT** [comment]
@sismo68, thank you.   so your GID+OpenSeesV2.8.0 is functionablely working with GID 14.0.1 , opensees v3.2.2, ActiveTcl-8.6.9? or other GID, TCL versions correspondingly? sorry for so many questions

**Comment by sismo68** [comment]
It works with gid 15 as well. Just follow the order of software
installation.

**Comment by szl-opensees** [comment]
> @sismo68 @cysorianoc thank you for all your discussions. as @cysorianoc mentioned, the OpenSees v3.2.1 can not be found anywhere. if possible, could you @sismo68 send me .zip file of OpenSees v3.2.1 to email: [yctang.dlut@foxmail.com](mailto:yctang.dlut@foxmail.com). thank u so much

I really need this version,could you send me .zip file if OpenSees v3.2.1 to email : m15032378289@163.com ; thank you so much.

**Comment by gordanagg** [comment]
@szl-opensees @sismo68 could you send me .zip file of OpenSees v3.2.1 to email: goga.cogy@gmail.com?
Thank you!

**Comment by vpapanik** [comment]
Check pinned posts before writing here.
