### ISSUE TITLE
Issue: Analysis has crashed

### ISSUE THREAD

**Issue by Kennethsq96** [rclab-auth/gidopensees#132]
Hello, my name is Kenneth. Today I started using OpenSees (Version 3.2.2 64-bit) with GID 15 and GID+OpenSees 2.8.  By doing this example (Plane Frame - Static and Modal Analysis (Elastic, 1D Elements) I followed step by step the instructions on the video, but when I tried to create the .tcl file and run the analysis I got this message that warned me about an error. I tried a lot of examples and every time I run the analysis I got the same warning message.

¿Could anyone please help me? 

The message I got:
![image](https://user-images.githubusercontent.com/70044091/90946173-c3ca7f80-e3e7-11ea-96bd-756f355b9ab8.png)

The .log file
![image](https://user-images.githubusercontent.com/70044091/90946338-13f61180-e3e9-11ea-8181-5fcb2638a7a6.png)

**Comment by poojaprajapati2229** [comment]
I have also same problem

**Comment by vpapanik** [comment]
There is no ActiveTcl 8.6.10 for the moment, it seems that OpenSees 3.2.2 works with 8.6.10. Try using OpenSees 3.2.1.

**Comment by poojaprajapati2229** [comment]
Ok sir 👍

**Comment by gordanagg** [comment]
@vpapanik dear professor, I tried to do Tutorial 4 - Nonlinear Reversed Cyclic Static Analysis on Beam-Column Joint, and I can't get results as in students work (Theocharis Kartalis Kaounis). This is the first time I have used Gid+Opensees, so I wonder if you could help me see where I'm wrong. 
Grateful in advance

![Interval_2](https://user-images.githubusercontent.com/73073680/96698888-eba97580-138d-11eb-9563-a56526ecf88e.png)
![results](https://user-images.githubusercontent.com/73073680/96698889-ec420c00-138d-11eb-9c56-f38314504b97.png)
