### ISSUE TITLE
ANALYSIS FAILED

### ISSUE THREAD

**Issue by poojaprajapati2229** [rclab-auth/gidopensees#133]
![Screenshot (38)](https://user-images.githubusercontent.com/70713245/92777725-1501d980-f3be-11ea-8a96-56850f4fdb42.png)

**Comment by poojaprajapati2229** [comment]
Hello,.  I usE OpenSees (Version 3.2.2 64-bit) with GID 15 and GID+OpenSees 2.8.0 I try example  I followe step by step instructions from Gid+Opensees interface introductory course , but when I tried to  run the analysis i got an error every time with all examples

**Comment by Kennethsq96** [comment]
I think the problem is due to the compatibility of version 2.8 of GID + OPENSEES with version 3.2.2 of OpenSees. I have the same problem and I have not been able to fix it. We have to look for version 3.2.1 and test it

**Comment by poojaprajapati2229** [comment]
Thank you sir for help .
