### ISSUE TITLE
Import Geometry from existing .tcl

### ISSUE THREAD

**Issue by akki21686** [rclab-auth/gidopensees#134]
Dear GiDOpenSeeS team

First of all, I should appreciate your efforts for providing this helpful graphical interface.

I have a problem with importing .tcl files. The first option in "Gid+OpenSees" tab.
I tried many .tcl files but each time I encountered with this error : "Could not import model geometry".

[quad.zip](https://github.com/rclab-auth/gidopensees/files/5255218/quad.zip)

**Comment by vpapanik** [comment]
You can send us your files in order to check them out.

**Comment by akki21686** [comment]
I have uploaded tcl file.

**Comment by Jerry-crj** [comment]
> You can send us your files in order to check them out.

Dear Professor:
I‘ve got the same problem when I attmpted to import the model from file.tcl, including the model which could be downloaded from the website ["https://github.com/rclab-auth/gidopensees/wiki/Examples"](url) 
[Example - Plane Frame on Elastic Soil - Pushover Analysis.zip](https://github.com/rclab-auth/gidopensees/files/5287164/Example.-.Plane.Frame.on.Elastic.Soil.-.Pushover.Analysis.zip)
