### ISSUE TITLE
Post Processing issue with GID+OpenSees v. 2.7.0

### ISSUE THREAD

**Issue by domenicogaudio89** [rclab-auth/gidopensees#135]
Dear GID+OpenSees team, 

I have been having an issue about post-processing for the last two weeks, whereas I didn't have to face any issue before (something has suddenly changed, I really do not know why).

I am using GID + OpenSees interface v. 2.7.0 as link between OpenSees v. 3.1.0 (Active Tcl 8.6, as suggested in one of the previous posts) and GID v. 14.0.3. They worked together perfectly till 2 weeks ago, allowing me to create and view the input .tcl file, run the analysis and then postprocessing the results, all authomatic.

Now, I can create and view the .tcl file and then run my own analysis as before, but then I cannot postprocess results automatically. Indeed, now I have to move the obtained .out files from the folder where the executable OpenSees.exe file is located to the folder OpenSees into the project .gid, where the .tcl file is in. Only then, I can ask GID+OpenSees interface to post process results so as to obtain the .post.res file. Actually, I obtain a .post.res.ascii file: hence, I have to delete the .ascii extension to make the interface read the results, but I always get some mistake this way (e.g. "cannot read Gauss points..." and therefore I cannot read any stress in Quad or Brick element).

To me, it seems that the .exe files located in the path C:\Program Files\GiD\GiD 14.0.3\problemtypes\OpenSees.gid\exe (as TclToGiD.exe and OpenSeesPost.exe) are not working automatically so that I have to call them "manually".

I obviously uninstalled and then installed again both GID and GID+OpenSees interface, but nothing changed. I also removed any Windows defender or similar checks on the above-mentioned .exe files, so that they are not stopped by any security procedure.

Any idea on how to solve this issue?

I would really appreciate.

Many thanks,
Domenico

**Comment by rafmuvdi** [comment]
Hi Guys:
Domenico:
Are all instalation files for the versions you mentioned still there in the Web?
If so, provide the links.
I would appreciate that.
Thanks,
RafMuvdi.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Kennethsq96** [comment]
@domenicogaudio89 Hi, could you send me OpenSees V3.1.0 and  OpenSees interface v. 2.7.0?  (kennethsq96@gmail.com)

I have problems with the current version of opensees and the interface. I can't find old versions of these programs on the web and I really need them.

Thank you very much in advance!

**Comment by vpapanik** [comment]
OpenSees 3.2.2 does not work with ActiveTcl 8.6.9, it seems that 8.6.10 is needed, but there are no installation for that. Try using OpenSees 3.2.1 for the moment.

**Comment by domenicogaudio89** [comment]
Dear Prof. @vpapanik ,

first of all I would like to thank you for your answer.

I have to admit that I did not understand why you referred to the OpenSees 3.2.2: the issue I reported here was observed with the OpenSees 3.1.0, that is working fine with the Active Tcl 8.6.
Indeed, the OpenSees .exe 3.1.0 allowed me to obtain the .out files I needed: the problem I reported is related to post processing, and therefore (I assume) to the GID+OpenSees interface.

Do you have any idea on how to solve the above-mentioned problem?

Thank you in advance.

Kind regards,
Domenico Gaudio

**Comment by domenicogaudio89** [comment]
Dear @rafmuvdi ,

as far as I know, unfortunately the GID+OpenSees v.2.7.0 is not available anymore on the web. Prof. @vpapanik kindly provided us with several versions of OpenSees, while the OpenSees v. 3.1.0 cannot be downloaded anymore. 

The only link I can send you is the one for downloading the GID v.14.0.3 (https://www.gidhome.com/download/official-versions/win64/).

I hope this can help you.

Best,
Domenico Gaudio

**Comment by rafmuvdi** [comment]
Thanks Domenico,
I ll give it a shot.
RM

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: domenicogaudio89<mailto:notifications@github.com>
Enviado: Saturday, September 26, 2020 6:33 AM
Para: rclab-auth/gidopensees<mailto:gidopensees@noreply.github.com>
CC: rafmuvdi<mailto:rafmuvdi@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [rclab-auth/gidopensees] Post Processing issue with GID+OpenSees v. 2.7.0 (#135)


Dear @rafmuvdi<https://github.com/rafmuvdi> ,

as far as I know, unfortunately the GID+OpenSees v.2.7.0 is not available anymore on the web. Prof. @vpapanik<https://github.com/vpapanik> kindly provided us with several versions of OpenSees, while the OpenSees v. 3.1.0 cannot be downloaded anymore.

The only link I can send you is the one for downloading the GID v.14.0.3 (https://www.gidhome.com/download/official-versions/win64/).

I hope this can help you.

Best,
Domenico Gaudio

**Comment by vpapanik** [comment]
The installation instruction have been updated.
However, there's no sign of ActiveTcl 8.6.10 yet... :(

**Comment by sadaf14212** [comment]
Hi
I want gid opensees interface 2.7.0
Anyone are help me
Tanks

**Comment by domenicogaudio89** [comment]
[GiDOpenSees_270_Setup (1).zip](https://github.com/rclab-auth/gidopensees/files/13532052/GiDOpenSees_270_Setup.1.zip)
Here it is @sadaf14212; hope this helps

**Comment by sadaf14212** [comment]
tanks alot
    On Saturday, December 2, 2023 at 02:01:00 AM GMT+4:30, domenicogaudio89 ***@***.***> wrote:  
 
 


GiDOpenSees_270_Setup (1).zip
Here it is @sadaf14212; hope this helps
