### ISSUE TITLE
Older OpenSees versions

### ISSUE THREAD

**Issue by vpapanik** [rclab-auth/gidopensees#136]
This might be helpful :

**https://www.dropbox.com/sh/uau7mcb8zuwk2fc/AABcQxlVv0fNb5Imw2kZmvN1a?dl=0**

**Comment by rafmuvdi** [comment]
.Thanks.
I appreciate it.
R.M

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rafmuvdi** [comment]
Thanks Professor Vassilis Papanikolaou for the Link.
I did manage to install the  O.S 3.21 program and GID 15 and The InterFace 2.8 and Tcl8.6. It is running, but I have to check results.
Thanks again.
R.M.



[cid:image002.png@01D69454.C637D5C0]

**Comment by vpapanik** [comment]
Not needed anymore.
v2.9.0 has an All-in-One installation working with the latest OpenSees 3.3.0.
