### ISSUE TITLE
Error in postprocessing regarding stresses

### ISSUE THREAD

**Issue by VinithKrishna** [rclab-auth/gidopensees#139]
This error has popped up in the post-processing and I'm unable to view stresses.
Some errors found in the results file:
Gauss points 'stdBrick_GP' not defined, 
![Try2SSB error](https://user-images.githubusercontent.com/72738985/97856919-fc110700-1d22-11eb-94cd-197061005a55.JPG)

Thanks in advance

**Comment by vpapanik** [comment]
Please send your model. It's probably an easy fix on the OpenSeesPost.

**Comment by VinithKrishna** [comment]
Dear Sir,

Thank you very much for your response. I'm attaching the model as you mentioned. Thanks in advance for your help.
[Try2SSB.gid.zip](https://github.com/rclab-auth/gidopensees/files/5474078/Try2SSB.gid.zip)

Thanks and Regards,
Vinith Krishna

**Comment by vpapanik** [comment]
@VinithKrishna  thanks for your feedback. The bug has been corrected in OpenSeesPost.exe. You can download this single file (v2.8.1) from the code repository and replace the existing one. Please report back.

**Comment by VinithKrishna** [comment]
It's working. Thanks a lot, Sir.

**Comment by VinithKrishna** [comment]
It's working. Thanks a lot, Sir.

**Comment by VinithKrishna** [comment]
It's working. Thanks a lot, Sir.

**Comment by VinithKrishna** [comment]
> @VinithKrishna thanks for your feedback. The bug has been corrected in OpenSeesPost.exe. You can download this single file (v2.8.1) from the code repository and replace the existing one. Please report back.

It's working. Thanks a lot, Sir.
