### ISSUE TITLE
Section Aggregator

### ISSUE THREAD

**Issue by FabioR88** [rclab-auth/gidopensees#14]
Hello GiD+OpenSees staff,
thanks a lot for your work in developing an easy and quick way to use OpenSees!
I'd like to know if it's possible at the moment to combine a Section Aggregator option to a concrete Fiber patch section.
Thanks you again,
Best,
Fabio

**Comment by vpapanik** [comment]
Thanks a lot Fabio for your excellent suggestion. This would be a great add in order to model pushover analysis with a shear failure criterion right ? We will look upon this issue for possible integration in the next versions.

**Comment by vpapanik** [comment]
for the moment, you can create the model using the interface, select 'Create and view .tcl', manually edit the .tcl file to include your section aggregator and then select 'Run analysis only and postproceess' option.

**Comment by vpapanik** [comment]
The feature will be included in the upcoming v2.1.0

**Comment by FabioR88** [comment]
Great!
Thanks.

**Comment by vpapanik** [comment]
It's ready. Please download the new 2.1.0
