### ISSUE TITLE
I am modeling a simple frame (OpenSees) including plastic hinge in it with lateral loading but everytime i run the analysis same problem occurs and it is showing that Analysis has crashed? I am attaching tcl file in .txt format please help me in this and I am using the most updated version of Gid.

### ISSUE THREAD

**Issue by RajArora25** [rclab-auth/gidopensees#140]
[check.txt](https://github.com/rclab-auth/gidopensees/files/5369830/check.txt)

**Comment by iammix** [comment]
geomTransf should look like the attached image. You deleted necessary components of geomTransf command.

![image](https://user-images.githubusercontent.com/25987029/96239802-d22cb600-0fa8-11eb-8782-9dea0cde0e8e.png)
