### ISSUE TITLE
Gid+OpenSees interface for Ubuntu

### ISSUE THREAD

**Issue by dunic** [rclab-auth/gidopensees#142]
Is it possible to use Gid+OpenSees interface on Ubuntu?

**Comment by vpapanik** [comment]
Out of the box, it runs only on Windows machines. But it can be easily transferred to Linux with some development, based on the already provided source code.

**Comment by dunic** [comment]
Thank you very much for your answer, but could you please share some instructions what is necessary to change/develop?
