### ISSUE TITLE
GiD+OpenSees is not working for fire 

### ISSUE THREAD

**Issue by VinithKrishna** [rclab-auth/gidopensees#145]
I'm trying to work in fire analysis with OpenSees and interested in post-processing results obtained from GiD+OpenSees interface. But there are no elements/material related to thermal classes. How to proceed with fire analysis in OpenSees with GiD?  

I would be really thankful for your reply.

**Comment by vpapanik** [comment]
You should add your own material models if needed, there's a pinned post about that.
