### ISSUE TITLE
Can someone please help me resolve my issue below when I run the model? I attached my model

### ISSUE THREAD

**Issue by olvrramos** [rclab-auth/gidopensees#146]
Error in base file 'C:/Program Files/GiD/GiD 15.0.1/problemtypes/OpenSees.gid/../OpenSees.gid/OpenSees.bas' at line number 59: ElemsMatProp: element without material

comand:ElemsMatProp must be a char
Error in 'strcmp' or 'strcasecmp'. 
Error in base file 'C:/Program Files/GiD/GiD 15.0.1/problemtypes/OpenSees.gid/../OpenSees.gid/OpenSees.bas' at line number 59: Error into an *if expression

**Comment by olvrramos** [comment]
[SSI.gid.zip](https://github.com/rclab-auth/gidopensees/files/5525393/SSI.gid.zip)

**Comment by vpapanik** [comment]
Check mesh
It has 3 linear and 8 triangle materials which should not be there (and have no material).
