### ISSUE TITLE
Stress units

### ISSUE THREAD

**Issue by gnavarta** [rclab-auth/gidopensees#147]
When I change units 'OPENSEES_SI_KN_AND_M' to 'OPENSEES_SI_MN_AND_M', stress values are rigths (MPa), but legends says kPa. I'm using OpenSeesPost.exe v2.8.1.

**Comment by pancongjian** [comment]
I meet  the same problem, HOW to solve it? Legned title Units can't cant coincide with the units of preprocessing module

**Comment by vpapanik** [comment]
This is not possible to solve at the moment.
