### ISSUE TITLE
Nonlinear Reversed Cyclic Static Analysis

### ISSUE THREAD

**Issue by gordanagg** [rclab-auth/gidopensees#148]
Can someone help me resolve my issue? I attached my model.

Thanks in advance

[Nonlinear Reversed Cyclic Static Analysis.gid.zip](https://github.com/rclab-auth/gidopensees/files/5553758/Nonlinear.Reversed.Cyclic.Static.Analysis.gid.zip)
[Gid_logfile.docx](https://github.com/rclab-auth/gidopensees/files/5553759/Gid_logfile.docx)

**Comment by vpapanik** [comment]
Your model just has convergence issues, it runs fine otherwise.
