### ISSUE TITLE
The model can not run

### ISSUE THREAD

**Issue by dlutzgj** [rclab-auth/gidopensees#149]
GID 15.0.1 and opensees 3.2.2 have been installed. the path of opensees.exe has been added  when gid+openseesV2.8.0 was installed. it is E:\OpenSees_workplace\bin\opensees.exe in my laptop. In the past, I always put the model in folder which includes the opensees.exe file to calculate. And the model can be calculated successsful. However, when a very simple model was created by gid+opensee, it can not run. and the error message has not been shown in the DOS window. So I copy the .tcl file of the model to the  folder which includes the opensees.exe file (i.e. E:\OpenSees_workplace\bin\ in my laptop). the error message is that "couldn't read file "E:/OpenSees_workplace/lib/tcl8.6/clock.tcl": no such file or directory". In addition, I found that it always be this type error message after a few simple tests. It should be notice that active tcl is not installed. Because opensees folder includes the lib folder, and it includes tcl8.6 folder.
Anyone else can help me fix this error?

**Comment by TahirCOMSATS** [comment]
hi there..I think, you have use opensees version 3.2.1 with Gid+Opensees V2.8.0 and for that we need to install ActiveTCL 8.6.

**Comment by amarchisella** [comment]
Could you please provide the  open sees v3.2.1 .
It is currently impossible to download from the website. It has been superseed by v3.2.2.

**Comment by amarchisella** [comment]
Ok, my post is solved #136.
