### ISSUE TITLE
too small and unstrechable windows

### ISSUE THREAD

**Issue by lucky-smith** [rclab-auth/gidopensees#152]
The  Gid+Opensees interface windows on my computer (OS: Win 10 64bit,  GiD v14.1.10d, GiD+OpenSees Interface v2.8.0) are too small and unstretchable. Could someone kindly help me with this? Thanks a lot!

![too small window](https://user-images.githubusercontent.com/64506110/105012855-91e24580-5a79-11eb-8dc0-c2056883cc50.png)

![too small window2](https://user-images.githubusercontent.com/64506110/105012091-b689ed80-5a78-11eb-91e6-72b89814b9b1.png)

**Comment by lucky-smith** [comment]
I've found the cause of the problem. I also installed 4t Tray Minimizer, which may have a conflict with the Gid+Opensees interface. The Gid+Opensees windows become resizable if 4t Tray Minimizer is quit.

**But one more question: is it possible to set any Gid+Opensees window maximized when it is opened? Is there any related option in the Preferences settings? Thanks!**

**Comment by vpapanik** [comment]
No, you need a third party utility for that.
