### ISSUE TITLE
WARNING Path TimeSeries::Path TimeSeries() - out of memory 

### ISSUE THREAD

**Issue by Yahya-bit** [rclab-auth/gidopensees#154]
can some body help me how to solve this
WARNING Path TimeSeries::Path TimeSeries() - out of memory on opensees

[dashpots newss try1111.log](https://github.com/rclab-auth/gidopensees/files/5918976/dashpots.newss.try1111.log)

**Comment by vpapanik** [comment]
It seems like a RAM problem on your computer. It has nothing to do with the GiD+OpenSees interface.
