### ISSUE TITLE
i cant run

### ISSUE THREAD

**Issue by Yahya-bit** [rclab-auth/gidopensees#155]
[ezyzip.zip](https://github.com/rclab-auth/gidopensees/files/5919530/ezyzip.zip)

**Comment by vpapanik** [comment]
cannot check without the full GiD model

**Comment by ababylip** [comment]
It cannot run, the error message is as follows：

Error in base file 'C:/Program Files/GiD/GiD 15.0.3/problemtypes/OpenSees.gid/../OpenSees.gid/OpenSees.bas' at line number 59: ElemsMatProp: element without material

comand:ElemsMatProp must be a char
Error in 'strcmp' or 'strcasecmp'. 
Error in base file 'C:/Program Files/GiD/GiD 15.0.3/problemtypes/OpenSees.gid/../OpenSees.gid/OpenSees.bas' at line number 59: Error into an *if expression
