### ISSUE TITLE
getting participating mass from eigenvalue calculation

### ISSUE THREAD

**Issue by dvdstwn** [rclab-auth/gidopensees#156]
I calculated the eigenvalue of my model (see attachement) using "genBandArpack" solver. This solver however doest not give information about the participating mass of each mode. On the internet I read that I should use "fullGenLapack" solver to get the participating mass. When I used "fullGenLapack" in gidopensees, the calculation runs very long and it seems to be freezed.

Could you suggest the best way (solver or setting) to get the participating mass)

[app_n360_new_fe_ok1c_ok.gid.zip](https://github.com/rclab-auth/gidopensees/files/5942809/app_n360_new_fe_ok1c_ok.gid.zip)

**Comment by vpapanik** [comment]
Actually the default is fullGenLapack for eigenvalue analysis. However, I cannot run your model because it yields some unit errors. Do you run in v2.8.0 ?
