### ISSUE TITLE
Error in running "Analysis cannot run"

### ISSUE THREAD

**Issue by thienbuu1802** [rclab-auth/gidopensees#160]
When I create a model, and run it. the model cannot run and an announcement as in attach pic. Can any  one help me to solve this?
Thanks

![111111](https://user-images.githubusercontent.com/80902724/111636243-a2295d80-883b-11eb-9d5c-261807750fb8.PNG)

**Comment by iammix** [comment]
You have elements without a material assigned to them.

**Comment by cvdr888** [comment]
I have exactly the same error message.: 

Error in base file 'C:/Program Files/GiD/GiD 15.0.3/problemtypes/OpenSees.gid/../OpenSees.gid/OpenSees.bas' at line number 59: ElemsMatProp: element without material

comand:ElemsMatProp must be a char
Error in 'strcmp' or 'strcasecmp'. 
Error in base file 'C:/Program Files/GiD/GiD 15.0.3/problemtypes/OpenSees.gid/../OpenSees.gid/OpenSees.bas' at line number 59: Error into an *if expression

I need help on this issue.

**Comment by vpapanik** [comment]
There are elements on your model where no material has been assigned to. This may include lines that have been wrongly meshed. Check your model.
