### ISSUE TITLE
Not able to add ground motion data file to records

### ISSUE THREAD

**Issue by VK1610** [rclab-auth/gidopensees#163]
Hello ,
Iam working on V2.8.5 of Gid+Opensees in this iam not able to add ground motion data file to the records field. Iam getting a error msg saying file not found, i tried using .txt, .dat,.tsl and .sml files but all gave the same error msg. When i downloaded the verification example 8-C which is in V2.7 after transformation it ran without any error. Not sure where iam going wrong.  I tried to put the file in .exe folder and also in records folder but it resulted in the same error.
Your help in this regard is highly appreciated.
Thank you.

**Comment by lihuaiguang** [comment]
I have the same problem. No idea.

**Comment by ababylip** [comment]
I have the same problem，too. 【哭唧唧】

**Comment by cvdr888** [comment]
Same here!!

**Comment by vpapanik** [comment]
Issue solved in v2.9.0
You can select .txt and .dat files.

**Comment by cvdr888** [comment]
Thank you. What about previous models losing info whenever the version is updated? Will that occur if I download the new 2.9?

**Comment by cvdr888** [comment]
Here's the message from a model transformation: 

Transforming to problem type OpenSees
value Truss Elements not found in question definition _#CB#(_)
The data field _ has a non acceptable value in old problemtype
value Beam Column Elements not found in question definition _#CB#(_)
The data field _ has a non acceptable value in old problemtype
value Surface Elements not found in question definition _#CB#(_)
The data field _ has a non acceptable value in old problemtype
value Solid Elements not found in question definition _#CB#(_)
The data field _ has a non acceptable value in old problemtype
value Output in selected layers for ShellMITC4 and ShellDKGQ elements with LayeredShell sections not found in question definition _#CB#(_)
The data field _ has a non acceptable value in old problemtype
value Select output and specify layer numbers for up to three layers (A,B,C) not found in question definition _#CB#(_)
The data field _ has a non acceptable value in old problemtype
value UserRecorder not found in question definition Recorder:#CB#(_)
The data field Recorder has a non acceptable value in old problemtype
Material Elastic has diferent number of fields in the new problem type
Material Elastic_Perfectly_Plastic has diferent number of fields in the new problem type
Material Elastic_Perfectly_Plastic_with_Gap has diferent number of fields in the new problem type
Material Viscous has diferent number of fields in the new problem type
Material Viscous_Damper has diferent number of fields in the new problem type
Material Hyperbolic_Gap has diferent number of fields in the new problem type
Material PySimple1 has diferent number of fields in the new problem type
Material TzSimple1 has diferent number of fields in the new problem type
Material QzSimple1 has diferent number of fields in the new problem type
Material BondSP01 has diferent number of fields in the new problem type
Material Steel01 has diferent number of fields in the new problem type
Material Steel02 has diferent number of fields in the new problem type
Material Reinforcing_steel has diferent number of fields in the new problem type
Material Hysteretic has diferent number of fields in the new problem type
Material Ramberg-Osgood steel has diferent number of fields in the new problem type
Material Concrete01_(Zero_tensile_strength) has diferent number of fields in the new problem type
Material Concrete02_(Linear_tension_softening) has diferent number of fields in the new problem type
Material Concrete04_(Popovics_concrete) has diferent number of fields in the new problem type
Material Concrete06 has diferent number of fields in the new problem type
Material ConcreteCM has diferent number of fields in the new problem type
Material Auto_Zero_Length has diferent number of fields in the new problem type
Material Auto_equal_constraint has diferent number of fields in the new problem type
Created material 'Elastic_Isotropic C35/45' inherited from 'Elastic_Isotropic'
Created material 'Elastic_Isotropic Soil' inherited from 'Elastic_Isotropic'
Created material 'Standard_Brick_Element Concrete C35/45' inherited from 'Standard_Brick_Element'
Created material 'Standard_Brick_Element Soil Test' inherited from 'Standard_Brick_Element'
There are some differences between the old problem and the new one.


Does these differences influence the numerical solution?

**Comment by vpapanik** [comment]
Not at all. This is a standard procedure for every new version.
