### ISSUE TITLE
How to run eigenvalue analysis? 

### ISSUE THREAD

**Issue by lihuaiguang** [rclab-auth/gidopensees#164]
I  have the fowllowing msg while running the eigenvalue analysis: 

> WARNING invalid nodeId: C:/ActiveTcl/lib/reg1.3/tclreg13.dll - load nodeId 1 forces
> 
> Starting analysis at 08:21:35
> 
> Running interval 1
> 
> Running eigenvalue analysis
> 
> FullGenEigenSolver::solve() - the eigenvalue 10 is numerically undetermined or infinite
> WARNING: analysis .. existing TransientAnalysis exists => wipeAnalysis not invoked, problems may arise

Great appreciate your answer? Thank you.

**Comment by vpapanik** [comment]
Try the first 9 to see if there's a modeling error. maybe there's no 10th.

**Comment by 1okiii** [comment]
WARNING invalid nodeId: C:/ActiveTcl/lib/reg1.3/tclreg13.dll - load nodeId 1 forces

hello,I'm getting the same warning message, pls have you solved it？
This my Emile： loki225@163.com
