### ISSUE TITLE
Analysis has crashed

### ISSUE THREAD

**Issue by kramerchen** [rclab-auth/gidopensees#166]
I did the examples the same as the official video ,but it still could not calculate.
version: gid:15.0.3 gid+gidopensees_285+opensees3.3.0 x64 windows.
can you help me?how to deal with?
<img width="249" alt="3e800969ace3e7e7d479324b6dad46c" src="https://user-images.githubusercontent.com/92258037/136696975-f533e858-f381-4b4a-85ba-e0f2c3b7b7e6.png">

**Comment by uribeza** [comment]
Hi All, same versions, I am getting the same issue trying to run a downloaded tutorial (plane frame). Tcl file is generated but analysis crashes. Thanks for hints

#

**Comment by vpapanik** [comment]
check if the generated .tcl runs in OpenSees using the command line. If it doesn't it means that your OpenSees installation is bad.

**Comment by vpapanik** [comment]
Try the new v2.9.0
