### ISSUE TITLE
Steel strucure

### ISSUE THREAD

**Issue by admodadmod** [rclab-auth/gidopensees#169]
Hi,
how we can build a steel section (W-section or I-section)?
Gid opensees is only for concrete structures?

**Comment by zgz115** [comment]
I have the same question. Who can help solve it?

**Comment by vpapanik** [comment]
The interface is open source so you can develop whatever section you want.
You can also use the General section where you specify the section properties.

![image](https://user-images.githubusercontent.com/22118061/151140778-d8453c00-78fc-4a65-896c-5cabe4d0fdd3.png)
