### ISSUE TITLE
GiD is not installed. Please install GiD to continue.

### ISSUE THREAD

**Issue by awa5114** [rclab-auth/gidopensees#17]
I am getting above error message when trying to install gid interface. I have a full version of GiD 12.0.9 installed and it is working smoothly. I am not sure why I am getting this message.

**Comment by vpapanik** [comment]
Check the registry

HKEY_CURRENT_USER\SOFTWARE\cimne\GiD

is this key there ?

**Comment by awa5114** [comment]
I'm afraid our company does not provide administrative privileges to it's users... I have no access to regedit Any other way to troubleshoot this problem? Perhaps there is a way to view the registry without editing it?

**Comment by vpapanik** [comment]
OpenSeesPot.exe is installed via the installer.
You should install the interface with administrative rights, just like any other piece of software, so you have to contact your administrator since you are in a restricted environment.
