### ISSUE TITLE
cannot see post processing after adding shear wall

### ISSUE THREAD

**Issue by admodadmod** [rclab-auth/gidopensees#170]
Hi,
I modeled the 3d-frame example. I ran the model and the model worked. Also, I checked post-processing and it worked and I saw forces, deformations, among others.

I add a shear wall using ShellDKGQ  in one span of Frame. I ran the model again after the analysis finished,  I checked post-processing but I cannot see the model. Can you help me why this happen?

**Comment by vpapanik** [comment]
please send the GiD model to check it out. It may be an issue in OpenSeesPost.exe (source is available)
