### ISSUE TITLE
Recordview.exe was unable to open the file.

### ISSUE THREAD

**Issue by ababylip** [rclab-auth/gidopensees#171]
Recordview.exe was unable to open the file. Errors such as "invalid conversion from string" "to type" double "and" arithmetic operation export "occurred.

**Comment by ababylip** [comment]
> Recordview.exe was unable to open the file. Errors such as "invalid conversion from string" "to type" double "and" arithmetic operation export "occurred.

**Comment by ababylip** [comment]
Now Recordview.exe can open the. txt file of ground motion data record, but GID + OpenSees still can't open it.

**Comment by vpapanik** [comment]
check answer in issue #172

**Comment by vpapanik** [comment]
check answer in issue #172
