### ISSUE TITLE
Problem with seismic record

### ISSUE THREAD

**Issue by Saimmy** [rclab-auth/gidopensees#172]
Hello. I have a problem with a seismic record, when I try to save with GID opensees in .dat or .txt format I get that the record does not exist. How do you enter a seismic record?
Seismic record is in the directory but it shows file does't exist

![Screenshot 2021-12-27 141956](https://user-images.githubusercontent.com/96725866/147466689-6cc7e411-6444-4e65-9254-d7a4a0d680c5.png)

**Comment by cvdr888** [comment]
I have exactly the same problem. Did you had any help? Do you already have any idea how to fix it?
Thank you, 
CR

**Comment by Saimmy** [comment]
you can go with this Fb post of mine (see comment Section)

https://www.facebook.com/groups/opensees/permalink/10158684067816492/

**Comment by cvdr888** [comment]
Apparently, your suggestion is working on version 15.0.3. 
Thank you!!!

**Comment by vpapanik** [comment]
This turned to be a GiD 15.0.3 issue (while 15.0.2 works ok) and will be subsequently corrected in the next version 15.0.4.

Till then you can do two things : 
1) rename the record file and delete its extension e.g. record.dat -> record
2) edit GiD 15.0.3\problemtypes\OpenSees.gid\tcl\Records.tcl and change

              set types [list [list [_ "All files"] ".*"]]
                set defaultextension ""

to

              set types [list [list [_ "Record file"] ".txt"] [list [_ "All files"] ".*"]]
                set defaultextension ".txt"

where e.g. .txt is the extension you are using in your record file.
That should fix the problem for now.

**Comment by vpapanik** [comment]
Solved in new version 2.9.0
You can select .txt and .dat files for records.
Issue closed
