### ISSUE TITLE
Query regarding analysis in openseesgid

### ISSUE THREAD

**Issue by rebbavishal272** [rclab-auth/gidopensees#173]
Sir, I have a problem in analysis part it is showing that analysis has been crashed. I did example problem of Masnory structure with concrete slab. I downloaded your model files but I am unable run this files. Please help me. 
My installation process is also checked thoroughly
![IMG_20211229_111502](https://user-images.githubusercontent.com/96809893/147630784-b58c219d-6869-4364-b0b0-a8304dfefbcc.jpg)

I read log file too but I couldn't figure it out.

**Comment by Saimmy** [comment]
i am unale to see attached image .


which version of opensees you are using ???
Try this
use Opensees 3.2.1
you can download  opensees3.2.1 from below link
https://www.dropbox.com/sh/uau7mcb8zuwk2fc/AABcQxlVv0fNb5Imw2kZmvN1a?dl=0&fbclid=IwAR0qesJtPU8KdvFAk-RLCqRYgxlNjmO1XaAEfhS8bG57FS7jN3N_RTIHVWs

**Comment by vpapanik** [comment]
Check whether the generated .tcl file can run in OpenSees in command line. If not, there's something wrong with your OpenSees installation.

**Comment by cbpilapil** [comment]
Hello Sir, mine says "analysis could not run". I already followed the proper installation procedure. I also tried making a simple box structure with fixed supports. It works fine with a simple structure. However when I tried to model my structure which is more complex, the said dialogue pops up. 

I also tried to run it in OpenSees but it just closes down when I press enter. I tried to record it when I try to run it in OpenSees and played in slow motion. It says:

PDeltaCrdTransf3d: :getLocalAxes
vector v that defines plane xz is parallel to x axis
ElasticBeam3d: :setDomain tag: 5 -- Error initializing coordinate transformation

Hope you can help me. Thank you!
![model](https://user-images.githubusercontent.com/99378072/153331490-07786d1c-24b2-4478-ab60-15bb38b3e2d2.PNG)

**Comment by cbpilapil** [comment]
[Model.zip](https://github.com/rclab-auth/gidopensees/files/8038520/Model.zip)

Attached is the gid file of my model. 

Hoping for your response. Thanks a lot!

**Comment by vpapanik** [comment]
Yes, there's an issue in the code regarding coordinate accuracy.
Try to fix your model coordinates to e.g. three significant digits (millimeters).
It looks like you have imported it from somewhere else, so fix the import tolerance to 0.001
![image](https://user-images.githubusercontent.com/22118061/153412643-bd0f9176-ce5a-494d-a37a-14d73b7fb56b.png)

**Comment by cbpilapil** [comment]
Hello Sir. Thank you for your response. Regarding the import issues, maybe it's not about it sir since I made the model from scratch in the GiD+OpenSees Interface.

**Comment by vpapanik** [comment]
So how did you end up with so many significant digits in your node coordinates ?

**Comment by cbpilapil** [comment]
I think it is because I used the cylindrical coordinate to plot my nodes (since 2 sides of my structure are oriented to a certain angle)

**Comment by vpapanik** [comment]
done
