### ISSUE TITLE
Version 2.9 can't run in GiD 14.0.2!

### ISSUE THREAD

**Issue by najafice** [rclab-auth/gidopensees#174]
Hi, 
I installed new version of GiD+OpenSees (2.9) in GiD version 14.0.2, But I face this error, How can I fix this?
It seems there's a file missing in the installation directory named "Tester.tcl".

`Error (l685): can't find package gid_graph
STACK:
can't find package gid_graph
    while executing
"package require gid_graph"
    (file "C:/Program Files/GiD/GiD 14.0.2/problemtypes/OpenSees.gid/tcl/Tester.tcl" line 2)
    invoked from within
"::gidutils::source {C:/Program Files/GiD/GiD 14.0.2/problemtypes/OpenSees.gid/tcl/Tester.tcl}"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 ::gidutils::source $args"
    (procedure "source" line 7)
    invoked from within
"source [file join $dir tcl $filename]"
    (procedure "::InitGIDProject" line 10)
    invoked from within
"::InitGIDProject {C:/Program Files/GiD/GiD 14.0.2/problemtypes/OpenSees.gid}"`

**Comment by vpapanik** [comment]
Yes, you should install the latest GiD 15.0.3
