### ISSUE TITLE
Error (l685): can't find package gid_graph

### ISSUE THREAD

**Issue by admodadmod** [rclab-auth/gidopensees#178]
Hi
I did the following step :
Download OpenSees and the associated tcl/tk framework. Install tcl framework and copy OpenSees.exe in any folder (recommended : C:\OpenSees). Please note that GiD+OpenSees Interface requires the full tcl/tk framework to run properly. If you are using the latest version of OpenSees, please install ActiveTcl 8.6 first, delete any tcl/tk files in the OpenSees folder and keep only the OpenSees executable.

Download GiD and install. Run and select Evaluation version (max 1010 nodes).

Download latest GiD+OpenSees Interface and install. During installation select the folder where OpenSees.exe was previously installed. If there are more than one GiD versions installed, the OpenSees problemtype is installed on the latest GiD version.

when in  GID I select Data → Problem type → OpenSees, the following error was appeared:
Error (l685): can't find package gid_graph
STACK:
**can't find package gid_graph
    while executing
"package require gid_graph"
    (file "C:/Program Files/GiD/GiD 14.0.1/problemtypes/OpenSees.gid/tcl/Tester.tcl" line 2)
    invoked from within
"::gidutils::source {C:/Program Files/GiD/GiD 14.0.1/problemtypes/OpenSees.gid/tcl/Tester.tcl}"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 ::gidutils::source $args"
    (procedure "source" line 7)
    invoked from within
"source [file join $dir tcl $filename]"
    (procedure "::InitGIDProject" line 10)
    invoked from within
"::InitGIDProject {C:/Program Files/GiD/GiD 14.0.1/problemtypes/OpenSees.gid}"**

**Comment by vpapanik** [comment]
use GiD 15.0.3 or later
no need to install tcl/tk framework
download GiD interface v2.9.5
read the readme file first before posting here
