### ISSUE TITLE
nodal masses of Shell elements in eigenvalue/dynamic analyses

### ISSUE THREAD

**Issue by Ballasty** [rclab-auth/gidopensees#180]
Hi, I am using GID+Opensees for eigenvalue and dynamic analysis of shear walls discretized using ShellDKGQ. I learned that dead load could be calculated automatically using mass density entered in the "element window" and these "vertical loads" could be applied automatically on the structure in the gravity analysis. I am wondering if nodal masses could be updated and assigned to nodes of these elements (in the similar way to that for dead loads) in order to perform eigenvalue/dynamic analyses?

Thanks, 
Bal

**Comment by vpapanik** [comment]
Yes, you just have to specify mass density in the material you assign to those shell elements.
