### ISSUE TITLE
Can't Load Problem Type "OpenSees" in GiD Windows 11 

### ISSUE THREAD

**Issue by Geo23Ham** [rclab-auth/gidopensees#181]
Could you please help me what is the issue? 

Screenshot here: https://www.linkpicture.com/view.php?img=LPic63c3176584d4d449232773 

https://www.linkpicture.com/q/2023-01-14_23h51_31.jpg 

[https://www.linkpicture.com/q/2023-01-14_23h51_31.jpg](url)

**Comment by vpapanik** [comment]
Try the latest GiD version
