### ISSUE TITLE
Can't find package gid_graph

### ISSUE THREAD

**Issue by LXZ-2022** [rclab-auth/gidopensees#183]
Error (l685): can't find package gid_graph
STACK:
can't find package gid_graph
    while executing
"package require gid_graph"
    (file "C:/Program Files/GiD/GiD 14.0.1/problemtypes/OpenSees.gid/tcl/Tester.tcl" line 2)
    invoked from within
"::gidutils::source {C:/Program Files/GiD/GiD 14.0.1/problemtypes/OpenSees.gid/tcl/Tester.tcl}"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 ::gidutils::source $args"
    (procedure "source" line 7)
    invoked from within
"source [file join $dir tcl $filename]"
    (procedure "::InitGIDProject" line 10)
    invoked from within
"::InitGIDProject {C:/Program Files/GiD/GiD 14.0.1/problemtypes/OpenSees.gid}"

**Comment by ningjiafei** [comment]
me too
