### ISSUE TITLE
Could not read clock.tcl file

### ISSUE THREAD

**Issue by AliAkbarSh** [rclab-auth/gidopensees#189]
Dear all,

I am using OpenSees Navigator 2.60 with OpenSees 3.50. When the model in run in Navigator, no post processing results such as mode shapes are shown. I investigated the problem by running the generated tcl file through the opensees command prompt and found that a error occurs which is "couldn't read file /lib/tcl8.6/clock.tcl": no such file or directory". Therefore no results are generated. 

Please assist me in how to locate the clock.tcl file or solve this problem. 

Regards,

**Comment by vpapanik** [comment]
This repository has nothing to do with OpenSees Navigator.
