### ISSUE TITLE
Initial bugs

### ISSUE THREAD

**Issue by jginternational** [rclab-auth/gidopensees#19]
Hi all!
I've installed the GiDOpenSees problemtype on GiDv13.1.7d and I'm finding some tcl errors

Global variables are not found (in OpenSees.tcl) since they are not declared global.
For example: 
`set GiDtheme "Classic"`
should be declared
`set ::GiDtheme "Classic"`
and so on.

When clicking in the Show/Hide Elements or Conditions, in the toolbar, the same errors happen:

> can't read "ConditionsDrawStatus": no such variable

So, I've fixed all this problems locally. I'll create a branch to push my changes here, and if you like the changes, could merge them into the master branch.

I use a different policy about problemtype variables (create them inside a namespace instead of global), but I don't want to change your policy.

Cheers
Javi G.

**Comment by vpapanik** [comment]
Dear Javi, thanks for your valuable input. 
Actually global vars worked prior to 13.1.7d, it's strange that they now need a  :: before.
Please push your changes in order to integrate them in the upcoming release.

**Comment by jginternational** [comment]
Hi @vpapanik 

I have no repository permission to push my branch

**Comment by vpapanik** [comment]
Don't worry, it has been corrected from our side and there will be a new release very soon.
