### ISSUE TITLE
Tri31 Element Output Error

### ISSUE THREAD

**Issue by ruslan-sa** [rclab-auth/gidopensees#193]
Hello Team, 

There appears to be an issue with the Tri31 element output. Please see details below. I was wondering if you might be able to check if this is a bug or whether this is an issue with my system? Thanks.

A 2D analysis of a split cylinder test was modelled in GiD-Opensees. The GiD postprocessing view shows the following error upon completion of the analysis:

![image](https://github.com/rclab-auth/gidopensees/assets/64298134/e96e1647-c107-48ab-b41d-1e1caa51a7b7)

The relevant output file line is shown here:
![image](https://github.com/rclab-auth/gidopensees/assets/64298134/111e76d0-0b87-4448-8420-2c9b0419fe8b)

Figure 1 shows the geometry of the model. Figure 2 shows the mesh composed of triangular elements. Figure 3 shows the restraints used at the bottom of the circle. Figure 4 shows the load applied at the top of the circle. Figure 5 shows the Tri31 element material properties used. Figure 6 shows the Tri31 element thickness.

Figure 1 - Geometry
![image](https://github.com/rclab-auth/gidopensees/assets/64298134/11615964-595f-43ff-a305-14c3ea9f0668)

Figure 2 - Mesh
![image](https://github.com/rclab-auth/gidopensees/assets/64298134/794415b7-5f71-4fc9-9bf4-1a027de77703)

Figure 3 - Restraints
![image](https://github.com/rclab-auth/gidopensees/assets/64298134/8f87f2a4-1aef-4eca-b61b-e05e0d64cb15)

Figure 4 - Loads
![image](https://github.com/rclab-auth/gidopensees/assets/64298134/8576f9ba-2f74-4590-ad0b-f61f44eada11)

Figure 5 - Elements - Material
![image](https://github.com/rclab-auth/gidopensees/assets/64298134/382c23d7-dfd9-42c2-9562-7cf7807716ca)

Figure 6 - Elements - Thickness
![image](https://github.com/rclab-auth/gidopensees/assets/64298134/e8635dd1-a489-4bd8-a4c0-a80138f0af29)

The analysis files are here:
[SplitCylinder4.gid.zip](https://github.com/rclab-auth/gidopensees/files/12709754/SplitCylinder4.gid.zip)

**Comment by vpapanik** [comment]
Thanks a lot for the bug report ! It has been now fixed.
Please download OpenSeesPost.exe file from the repository and replace the existing one.

https://github.com/rclab-auth/gidopensees/tree/master/exe

I wonder if it is possible to display the Tri31 strain as well, but 'strains' is not accepted as a recorder argument.
