### ISSUE TITLE
error in displacement-based beam column section

### ISSUE THREAD

**Issue by arinatac** [rclab-auth/gidopensees#21]
I'm Sorry i'm new to this gid+opensees. Thank you for your great work to make it easier to use opensees. I face a problem, why always i got error messages every time i tried creating .tcl for displacement based beam column. It is said that cross section area doesn't exist and problems set in var, and I thought i input everything right. Please help, thank you
![image](https://user-images.githubusercontent.com/31197120/29501886-15fdb3d2-8656-11e7-9668-984ab800b2be.png)

**Comment by vpapanik** [comment]
Hello and thanks for the feedback. The issue has been corrected in the next version v2.2.0 which will be released tomorrow.

**Comment by arinatac** [comment]
when will they release it?

**Comment by vpapanik** [comment]
just did

**Comment by arinatac** [comment]
thank you, can you include beam with hinges element?
