### ISSUE TITLE
Error-invalid command name "model"

### ISSUE THREAD

**Issue by HervertP** [rclab-auth/gidopensees#22]
sorry, I'm afraid I'm new using your program, I'm trying to run an example of your tutorial, but I get the message I attached ...
I would appreciate if you could help me with that problem, thank you very much
![image](https://user-images.githubusercontent.com/31839080/30259233-76671814-9685-11e7-867b-30358d0c7fc0.png)

![image](https://user-images.githubusercontent.com/31839080/30259238-86d4219c-9685-11e7-90b5-ea1f14b25f9f.png)

**Comment by darkwaves** [comment]
I have same issues too. if anyone can help me i'm will be so grateful

**Comment by vpapanik** [comment]
Could you please tell us which model you're trying to run, in order to reproduce the issue ? Or please attach a download link here.

**Comment by vpapanik** [comment]
We have updated all examples in the wiki page, please download again. Sorry for the inconvenience caused.
