### ISSUE TITLE
Couldn't create a new folder ?

### ISSUE THREAD

**Issue by burakduran** [rclab-auth/gidopensees#23]
Hello Dear Friends,

I am a new user of GID+Opensees program and trying to model a 2D RC Frame to learn how this program works. But, the problem is that I couldn't save the file at the end of modelling. 

Would you please say me what the problem is ? I can't understand, is it related to a folder where this Interface module installed in C disk ? 

Thank you in advance 

![screenshot 2017-09-27 09 54 31](https://user-images.githubusercontent.com/32166001/30899775-0440a858-a36a-11e7-898e-57d9a0ab8f80.png)

**Comment by vpapanik** [comment]
The folder you're trying to save has no user permission from windows. Try saving it in My Documents.
