### ISSUE TITLE
Can not read element local axes

### ISSUE THREAD

**Issue by arinatac** [rclab-auth/gidopensees#27]
I am working on my thesis and now running five-storey building with dynamic analysis and now moving to postprocess. unfortunately, when i am trying to postprocess, it can not read element local axes and opensees stopped because of error. here i upload my tck. Please help me. Thank ypu for your consideration
[Building.txt](https://github.com/rclab-auth/gidopensees/files/1431289/Building.txt)

**Comment by vpapanik** [comment]
Please zip the entire .gid folder and upload it. Do a reset analysis first and ensure that it has been transformed to the latest version 2.2.5.

**Comment by arinatac** [comment]
i am using the 2.2.5 gid+opensees. here is the zip, thank you so much for your help
[Amin.gid.zip](https://github.com/rclab-auth/gidopensees/files/1431379/Amin.gid.zip)

**Comment by vpapanik** [comment]
When using force-based and displacement-based elements, you should do a multistep inelastic static analysis. It seems that you have applied the whole load in one step. As a result the analysis cannot run in OpenSees.

Another thing : why using cross bracing on floor levels ; there are diaphragms for this.

**Comment by arinatac** [comment]
I have modified the tcl because i used beam with hinges instead of using force and displacement beam column. I then use cross bracing and connect it with rigidLink bar. The problem is, i couldnt proceed to postprocess.

**Comment by arinatac** [comment]
I am confused of multistep inelastic static analysis. What do i suppose to do?
