### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by joelsmith27** [rclab-auth/gidopensees#29]
Hi there,

Perhaps I've done something wrong with my setup. I can't even run an example file. I just get this message:

Error in base file 'C:/Program Files/GiD/GiD 13.0.3/problemtypes/OpenSees.gid/OpenSees.bas' at line number 226: Error in TCL expression: 'can't read "GiDProjectName": no such variable'

Regards,
Joel

**Comment by vpapanik** [comment]
Hello Joel, please try to uninstall any previous version first, and manually delete any leftover files in problemtypes/OpenSees and try to reinstall the interface. Please report back.

**Comment by sismo68** [comment]
Having a similar problem but in line 84: MatProperty...not found.. Even though all elements were assigned materials.

**Comment by kanagn** [comment]
Hello from me as well,

I am also having a similar problem when I am trying to run an analysis. I even tried to regenerate step by step some online examples but I am still getting a message that analysis failed to run in addition to the following error message:

"Error writing file for template : C:\Program Files\GiD\GiD13.0.4\problemtypes\OpenSees.gid/../OpenSees.gid/OpenSees.bas"

Any ideas?

Thanks

**Comment by vpapanik** [comment]
Check the new version v2.5.0. Do a clean install and please report back if the problem persists.
