### ISSUE TITLE
Model using Trusses and Beam

### ISSUE THREAD

**Issue by alva1977** [rclab-auth/gidopensees#30]
Is there a way we can use in the same model trusses and beams in GiD+OpenSees...

**Comment by vpapanik** [comment]
Yes, this is supported. Just draw your model and the .tcl file will contain all entities. Check the examples too.

**Comment by vpapanik** [comment]
However, you should manually provide EqualDOF constraints at nodes where trusses are connected with beams (e.g. Ux and Uy for the 2D case).
