### ISSUE TITLE
OpenSeesPost.dpr

### ISSUE THREAD

**Issue by alva1977** [rclab-auth/gidopensees#31]
I have included some new materials, sections and elements to GiD+OpenSees. Now I need to update OpenSeesPost.exe. I was wondering if you have a version of OpenSeesPost.dpr but in C or C++, so I could compile it using Visual Studio. Or, Does exist a free compiler for dpr files?

Thank you.

**Comment by vpapanik** [comment]
You can try the Delphi free started edition here : https://www.embarcadero.com/products/delphi/starter or try to port (and share) the code in another language.
