### ISSUE TITLE
program does not run

### ISSUE THREAD

**Issue by sismo68** [rclab-auth/gidopensees#33]
After reinstalling latest version (2.5.0) and model a simple 3d frame, the program still does not run (see images, and am attaching model). It would be good to be able to download one of the samples from videos for us to be able to check what is going on.
[sample_3d.zip](https://github.com/rclab-auth/gidopensees/files/1783084/sample_3d.zip)
![gid_opensees_retorno](https://user-images.githubusercontent.com/35981425/37007280-90c1b6a6-20aa-11e8-9137-7d58a2dc09c1.JPG)

**Comment by vpapanik** [comment]
Try a clean install. Delete the problemtypes/OpenSees folder from your GiD installation first, then re-install and retry. Don't forget to transform your model to the new version when prompted. The model you are attaching is not recognized by GiD, some file is missing apparently.

**Comment by vpapanik** [comment]
I renamed the folder to retorno.gid, now it opens with GiD and analysis was completed without problems. There's something wrong with your installation, after a clean install everything should work.

**Comment by vpapanik** [comment]
Check these https://github.com/rclab-auth/gidopensees/wiki/Examples
