### ISSUE TITLE
Problem When Changing Interval Data

### ISSUE THREAD

**Issue by ozgunnn** [rclab-auth/gidopensees#34]
When I modify the interval data or add a new one, select parameters and click "accept". I get the following error. How to solve this? Thanks in advance

Error in tcl script sending event SYNC to GidUtils::TkwidgetEntryConfigure {-width 50}: invalid command name "GidUtils::TkwidgetEntryConfigure {-width 50}"
    while executing
"$GidData($iproc) SYNC $GDN $StructName $QUESTION"
Error in tcl script sending event SYNC to GidUtils::TkwidgetEntryConfigure {-width 50}: invalid command name "GidUtils::TkwidgetEntryConfigure {-width 50}"
    while executing
"$GidData($iproc) SYNC $GDN $StructName $QUESTION"
    while executing
"error $result"
    invoked from within
"if [string equal $result CANCEL] {
            return
        } else {
            error $result
        }"
    (procedure "DWIntervalAccept" line 17)
    invoked from within
"DWIntervalAccept GD_INT_1"
    invoked from within
".gid.intvdata1.but.accept invoke "
    invoked from within
".gid.intvdata1.but.accept instate !disabled { .gid.intvdata1.but.accept invoke } "
    invoked from within
".gid.intvdata1.but.accept instate pressed { .gid.intvdata1.but.accept state !pressed; .gid.intvdata1.but.accept instate !disabled { .gid.intvdata1.but..."
    (command bound to event)

**Comment by vpapanik** [comment]
Please attach your model or try a clean install of the interface (delete the problemtypes/OpenSees folder and reinstall).

**Comment by ozgunnn** [comment]
I tried deleting and reinstalling the problem type but still had the same issue. I get the same error even without defining a model. Meaningly when i open Gid, load Opensees problem type, try to change interval data without modelling anything i still get this error.

**Comment by vpapanik** [comment]
What GiD version are you using ? I tried this on 13.0.3 without any problems.

**Comment by ozgunnn** [comment]
Mine is 13.0.4

**Comment by ozgunnn** [comment]
I tried version 13.0.3 now and it worked. Thanks a lot for the help.

**Comment by aminkotb** [comment]
the same problem with me.  I am using version 12.00

**Comment by vpapanik** [comment]
It will be fixed in the next version. For the time being, go to OpenSees.prb and put a # in front of line 170 : #TKWIDGET: GidUtils::TkwidgetEntryConfigure {-width 50}

**Comment by gopu16101989** [comment]
Thank you vpapanik and ozgunnn. I had the same problem and it was solved by using GiD Version 13.0.3.
