### ISSUE TITLE
Multiple Domains

### ISSUE THREAD

**Issue by ozgunnn** [rclab-auth/gidopensees#35]
I'm trying to model an SSI problem. Thus i will need to use solid elements (ndm 3, ndf 3) with beam elements (ndm 3, ndf 6). I create the model and gid writes the tcl code. The issue is with the tcl code.

-The model domain 2 which is supposed to have 6 dofs has 3 dofs in the script. 
-The assigned section properties of the beam aren't captured by the script (there is no beam element defined in the script although i modelled them in Gid+Opensees). 
-And the fixed nodes in the Domain 1 are again fixed in Domain 2 which makes Opensees to give warning. 

I could model my problem with modifying the tcl script but still wanted to share the issue here.

**Comment by vpapanik** [comment]
Thanks for your feedback. It is impossible to reproduce the problem without at least attaching your model to see what is going wrong. You can check the SSI examples on the Wiki and the user manual of course.

**Comment by ozgunnn** [comment]
Working further on it i noticed it happens when i have extra nodes on the model. I solved the issue first collapsing all the points on model and then uncollapsing the points only on the line element.

Though this time I have another issue. I have a respresentative model just to see if eigenvalue analysis works when i model solids together with beams with corresponding DOFs of same coordinates having equaldof constraints. Tcl code is generated properly but opensees analysis fails. It seems to me being related with opensees rather than Gid but still I would like to know your opinion why and I'm attaching my Gid model.

Thanks in advance.

[solid+piledeneme.gid.zip](https://github.com/rclab-auth/gidopensees/files/1799699/solid.piledeneme.gid.zip)

**Comment by vpapanik** [comment]
Unfortunately I cannot run the model because I am using the evaluation version of GiD.

**Comment by ozgunnn** [comment]
Howcome? It's just 29 nodes.

**Comment by vpapanik** [comment]
There is also a 25-surface limit !
