### ISSUE TITLE
Full Screen Toggle

### ISSUE THREAD

**Issue by gopu16101989** [rclab-auth/gidopensees#36]
I have installed GiD Version 13 on a Windows 7 operating system with the OpenSees add on. Once I go full screen and I use F11 to toggle back to normal screen, the toolbars disappear. Have any of you faced this issue? I am not sure if I am missing a trick here. Any kind of help is appreciated.

**Comment by vpapanik** [comment]
Yes, there's a problem when going fullscreen, the toolbar will stop working. Please use a maximized window instead.

**Comment by gopu16101989** [comment]
![gid_problem](https://user-images.githubusercontent.com/25394709/37730310-c1f73fbc-2d15-11e8-902a-8acb05fc263c.png)
 This is how my screen looks after maximized window with no toolbars. I have tried reinstalling GiD but it starts with no toolbars or menu bars.

**Comment by vpapanik** [comment]
go to C:\users\<username>\appdata\roaming\gid and delete everything there.

**Comment by gopu16101989** [comment]
Thank you so much vpapanik. Your last comment has cleared the problem. 
I appreciate your time and prompt replies.
