### ISSUE TITLE
Analysis could not run!

### ISSUE THREAD

**Issue by gopu16101989** [rclab-auth/gidopensees#37]
I am using GiD+Opensees to run the Tutorial: Plane Truss (Elastic, 1D elements) provided in the link below:
https://www.youtube.com/watch?v=8TqTgitJp0s&list=PLy36D5yzeU1fE0S0osYO5zLVS8JQ6tvEF

The problem is that I get the following error (shown in picture below) after I follow the steps exactly
![gid_problem2](https://user-images.githubusercontent.com/25394709/37734631-24552924-2d22-11e8-97c3-c52847b25ac2.png)
Any help or assistance is greatly appreciated.

**Comment by vpapanik** [comment]
There are a lot of changes since videos were made, so please attach your model here to check it out.

**Comment by gopu16101989** [comment]
![gid_problem3](https://user-images.githubusercontent.com/25394709/37735314-0bb16d68-2d24-11e8-8a8e-d79f25485fc0.png)
Boundary Conditions on Truss Elements made of Steel Members
![gid_problem4](https://user-images.githubusercontent.com/25394709/37735344-1d0c9506-2d24-11e8-8862-7faffd1f0872.png)
Vertical Load of -10kN on nodes as shown in figure above

**Comment by vpapanik** [comment]
I mean attach a zip file with the complete .gid folder

**Comment by vpapanik** [comment]
Also check whether you have NOT restrained any rotations at the four boundary conditions.

**Comment by gopu16101989** [comment]
[sampleTruss.gid.zip](https://github.com/rclab-auth/gidopensees/files/1835127/sampleTruss.gid.zip)
Sorry, I could not understand the first time. The nodes have two (translational) degrees of freedom only.

**Comment by vpapanik** [comment]
Your attached model ran fine on my system. I am attaching the produced .tcl file, please compare with yours. I am using OpenSees rev. 6345
[sampleTruss.zip](https://github.com/rclab-auth/gidopensees/files/1835496/sampleTruss.zip)

**Comment by vpapanik** [comment]
I found out that they are exactly same. In my system, it runs ok. Is it a matter of OpenSees revision ? I really don't know.

**Comment by gopu16101989** [comment]
The version that I am using is OpenSees Version 2.5.0 (rev 6536) 64 Bit. I have tried reinstalling OpenSees and running it. I still get the same problem.

**Comment by gopu16101989** [comment]
Are there any restrictions on the folder in which I save .gid files?

**Comment by vpapanik** [comment]
I tried running your model with rev 6536 too. Runs ok.
Maybe the problem is elsewhere.
I am using C:\OpenSees folder for placing OpenSees.exe, and installed the interface pointing at this folder. Use a folder inside \Documents to save your models (no restrictions). Please retry and report back. The model is 100% correct.

**Comment by gopu16101989** [comment]
During installation, the software says that OpenSees preferably has to be in the folder C:\OpenSees but it seems that it HAS to be (not preferably) that particular folder. This means that the person HAS to have administrator privileges to a computer to use this software. I had a different folder and did not work all this while. I changed the OpenSees folder to C:\OpenSees and it worked out. Thanks a lot vpapanik.

**Comment by vpapanik** [comment]
So you mean that it has to do with OpenSees folder, not the model folder. I am using My documents for my models and C:\OpenSees for the OpenSees executable without problems. But I suppose that yes, administrator privileges are needed for these programs to run properly (ability to save files on these folders).

**Comment by gopu16101989** [comment]
Yes, for me the problem was with the OpenSees folder. I was using a shared system initially and I could not install OpenSees in C folder. Subsequently, I used my personal laptop (saved OpenSees in C folder) and it worked.
