### ISSUE TITLE
Cann't define the nonlinear material use the fiber section

### ISSUE THREAD

**Issue by CIDP** [rclab-auth/gidopensees#38]
when I define the fiber section use the nonlinear materials the problem will occur. I use GiD13.03 and interface version is2.5.0. The problem is as follow:
can't read "GidData(MAT,Column section,SYNC,TKWIDGET)": no such element in array
can't read "GidData(MAT,Column section,SYNC,TKWIDGET)": no such element in array
    while executing
"error $result"
    invoked from within
"if [catch "DWCheckClose $GDN" result] {
        if [string equal $result CANCEL] {
            return
        }
        if {$after_close ne ""} {
    ..."
    (procedure "DWCloseWindow" line 4)
    invoked from within
"DWCloseWindow GD_MAT_6"
    invoked from within
".gid.materials6.but2.close invoke "
    invoked from within
".gid.materials6.but2.close instate !disabled { .gid.materials6.but2.close invoke } "
    invoked from within
".gid.materials6.but2.close instate pressed { .gid.materials6.but2.close state !pressed; .gid.materials6.but2.close instate !disabled { .gid.materials6..."
    (command bound to event)

**Comment by vpapanik** [comment]
It's impossible to reproduce the problem by this description. Please report what you do step-by-step in order to reproduce the error. The fiber sections seems to work fine on this version.

**Comment by CIDP** [comment]
Thank you Dr.  I think I have solve this problem. I will report problem more specific next time. 

Best wishes. 

Yang
