### ISSUE TITLE
QuadUP element Problem

### ISSUE THREAD

**Issue by gopu16101989** [rclab-auth/gidopensees#39]
I have DRY soil in a rectangular area height of 5.5 m and width of 14 m. The analysis is a plane strain analysis with QUAD elements. This works perfectly for a gravity run as shown in the folder attached below:
[simpleSoilDry.gid.zip](https://github.com/rclab-auth/gidopensees/files/1848330/simpleSoilDry.gid.zip)

Subsequently, I take the same model and assign QuadUP elements and run a gravity analysis to simulate saturated soil. OpenSees stops working. I checked the logfile and it says the BandLapack error. I changed it to ProfileSPD and I get same results. Please find the required folder below:
[simpleSoilSat3.gid.zip](https://github.com/rclab-auth/gidopensees/files/1848342/simpleSoilSat3.gid.zip)

Any kind of help or input is appreciated.

**Comment by gopu16101989** [comment]
I am using GiD 13.0.3 Evaluation Version with Opensees 2.5.0. I see the same problem with GiD 13.0.4 too.

**Comment by vpapanik** [comment]
It seems that both models you have attached have Quad elements...
please also report the OpenSees revision you are using.

**Comment by gopu16101989** [comment]
I have double checked the two attached zip file. simpleSoilDry.gid.zip has quad elements whereas simpleSoilSat3.gid.zip has quadUP elements. 
I am using OpenSees Version 2.5.0 (Version 6536).

**Comment by gopu16101989** [comment]
One is QUAD and the other is QUADUP.

**Comment by vpapanik** [comment]
can you please repost simpleSoilSat3.gid ? It seems that the tcl file inside has QuadUPs and the gid model has Quads without boundary conditions !
