### ISSUE TITLE
element without material

### ISSUE THREAD

**Issue by CIDP** [rclab-auth/gidopensees#40]
Dear Dr.

I plan to do egenvalue analysis for 3 stories RC frame structure infilled masonry walls. When I construct the model, assign the element and began to calculate, the problem occured as follow:
![no title](https://user-images.githubusercontent.com/37763121/37921885-a3cf50a0-315d-11e8-8d66-2548ed945b50.jpg)

I am not sure why this problem occur and could you help check my model?
[20180325-three story rc frame with nonlinear materials-masonry wall infilled.gid.zip](https://github.com/rclab-auth/gidopensees/files/1849124/20180325-three.story.rc.frame.with.nonlinear.materials-masonry.wall.infilled.gid.zip)

**Comment by vpapanik** [comment]
We used to have some issues with material/element names with spaces. We were told that this issue has been corrected in GiD 13.0.4, but I have just checked and it seems not. Please try to use material/element names without spaces.

Please check beam 3 has assigned material beam 2.
