### ISSUE TITLE
Soil structure interaction

### ISSUE THREAD

**Issue by aminkotb** [rclab-auth/gidopensees#41]
I am modeling a single bridge pier supported in pile cap considering soil-structure interaction as shown in the file.

- The piles are modeled as elastic force beam element. While the pier is modeled as nonlinear force beam element.

- The pile and pile cap are fully bonded to soil with EqualDOF in X and Y directions.

- The bridge weight and mass are applied to node 9515 at top of pier element. 

- The earthquake loads are applied as an equivalent force equal to (Lysmer-Kuhlemeyer constant * velocity) at node 117270.
 
- I have used "sp Constraint" to constrain base of the structure (nodes 1, 11726 and 117270 in X-direction during gravity analysis), then removed this constraint in earthquake analysis.

**I need your help on the following items:**

1.  Are the steps used in modeling and analysis correct or not. and how can I improve it?
2. The earthquake results show displacement osculation around an inclined line (not Zero). Also, the velocity at node (1) is shifted from the original input velocity. output results are plotted in the attached excel file.
3. Do I need to add additional damping to the model to count for structure and soil dampings (radiational damping) or is it inherited in soil material plastic behavior?

[Model.zip](https://github.com/rclab-auth/gidopensees/files/1849786/Model.zip)

Thanks and best regards

**Comment by vpapanik** [comment]
I am afraid that I cannot answer these technical questions here, since this section is only for issues concerning the GiD+OpenSees interface itself. You can try posting your question to the OpenSees forum, which is more appropriate for technical issues concerning the solver.
