### ISSUE TITLE
ContactMaterialnD

### ISSUE THREAD

**Issue by gopu16101989** [rclab-auth/gidopensees#42]
Are there any options to use ContactMaterialnD in GiD+OpenSees?

**Comment by vpapanik** [comment]
This material has not been implemented yet, but you can still edit the .tcl file manually and add this in your model. Then, you can select 'run analysis and postprocess'

**Comment by gopu16101989** [comment]
I manually changed my .tcl file. However, the post processed values appear similar to the run that I had made without the manual change. I am aware the output from GiD is saved in the folder named OpenSees inside the .gid file. However, once I manually change the .tcl file, I do not see any change in the outputs that are saved in the OpenSees folder inside .gid file. I would like to know the locations of  outputs that are saved after the "Run Analysis and Postprocess" application.

**Comment by vpapanik** [comment]
You are correct. Are you sure that you don't select any of the three first menu options ? these re-create the .tcl file. If you edit it manually and select the 'run analysis and postprocess' option, the file won't change, you can re-check it after analysis. Now, if the results are the same, then it has only to do with what is written inside the .tcl file, ie. it is an OpenSees issue only. You can attach the model folder here, together with the modified .tcl file in order for me to check if you like.
