### ISSUE TITLE
Problem with post-processing

### ISSUE THREAD

**Issue by tejeswar91** [rclab-auth/gidopensees#43]
Respected Dr. V. Papanikolaou,

I have modelled a 2D-truss with rigid connections using elastic beam-column elements and found the following problem while post-processing,

 1. Spanning along X-axis: OpenSees able to solve - Postprocessor working fine
 2. Spanning along Z-axis: OpenSees able to solve - Postprocessor is terminating with some error

I am also attaching here the problem files. Kindly help me with this and thanks in advance
[temp.zip](https://github.com/rclab-auth/gidopensees/files/1859554/temp.zip)

![image](https://user-images.githubusercontent.com/37624980/38083058-3042e320-337b-11e8-8f9b-8ddde3859f95.png)

**Comment by vpapanik** [comment]
It seems there's a bug in OpenSeesPost.exe. Will check it out and correct in the next update. Thanks for reporting this !!!

**Comment by vpapanik** [comment]
You can try the new v2.5.1, the issue has been corrected.

**Comment by tejeswar91** [comment]
thank you very much

**Comment by vpapanik** [comment]
It was again a roundoff error. Thanks for reporting. I have fixed the OpenSeesPost.exe file, please download and use. Unzip with 7z tool using your username as password.

[OpenSeesPost.zip](https://github.com/rclab-auth/gidopensees/files/1867581/OpenSeesPost.zip)

**Comment by tejeswar91** [comment]
Thank you very much. Now it is working great.
