### ISSUE TITLE
Problem with post-processing: Persisting

### ISSUE THREAD

**Issue by tejeswar91** [rclab-auth/gidopensees#45]
Respected Dr V. Papanikolaou,

Please refer to the problem #43

I have tried the new version (2.5.1). Post processing is working until two bays, while the same model with third bay or more is not working. I am attaching here the model files. Thanks in advance.

[fm1.gid.zip](https://github.com/rclab-auth/gidopensees/files/1867447/fm1.gid.zip)
![image](https://user-images.githubusercontent.com/37624980/38187031-6f2abf3a-3688-11e8-9d92-6054d9f8ab56.png)

**Comment by vpapanik** [comment]
check the original thread
