### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by talledodiego** [rclab-auth/gidopensees#47]
Error (l685): unable to get value "AppData" from key "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders": Impossibile trovare il file specificato.
STACK:
unable to get value "AppData" from key "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders": Impossibile trovare il file specificato.
    while executing
"registry get {HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders} {AppData}"
    (procedure "GetAppDataDir" line 9)
    invoked from within
"GetAppDataDir"
    (procedure "SetImagesAndColors" line 5)
    invoked from within
"SetImagesAndColors"
    (procedure "OpenSees::InitGIDProject" line 14)
    invoked from within
"OpenSees::InitGIDProject $dir"
    (procedure "::InitGIDProject" line 11)
    invoked from within
"::InitGIDProject {C:\Program Files\GiD\GiD 13.0.2\problemtypes\OpenSees.gid}"

**Comment by vpapanik** [comment]
What windows version are you using ? go to registry (regedit.exe) at this key 
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
and report back what is inside, in order to check.
Or try to run setup with administrator privileges.

**Comment by vpapanik** [comment]
What windows version are you using ? go to registry (regedit.exe) at this key 
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
and report back what is inside, in order to check.
Or try to run setup with administrator privileges.
