### ISSUE TITLE
Section recorder

### ISSUE THREAD

**Issue by sismo68** [rclab-auth/gidopensees#50]
The problem output does not contain section recorders when specifying fiber sections in a model. Where or which file could be modified to add section recorders (localforce, stressStrain, axial deformation, etc) for each of the sections in the 3 points where along the length of a force/displacement beam-colum element?

**Comment by vpapanik** [comment]
Υου can always edit the .tcl file and add the extra recorders you need. However, those would not be handled in postprocess, but you can use the results directly from your custom .out files
