### ISSUE TITLE
GiD Opensees problem

### ISSUE THREAD

**Issue by haldarsumanta** [rclab-auth/gidopensees#51]
I am trying to solve simple 3D beam problem using GiD OpenSees interface. However, I am getting the following error always!

WARNING BandGenLinLapackSolver::solve() -factorization failed, matrix singular U(i,i) = 0, i= 1
WARNING Linear::solveCurrentStep() -the LinearSOE failed in solve()
StaticAnalysis::analyze() - the Algorithm failed at iteration: 0 with domain at load factor 1
OpenSees > analyze failed, returned: -3 error flag

Analysis FAILED

Can anyone help me out !

**Comment by vpapanik** [comment]
Mostly like it is a boundary conditions issue, something forgotten. Check the .tcl file or attach your full model here to check.

**Comment by haldarsumanta** [comment]
Thank you @vpapanik 
I have provided all boundary conditions however it is not working. 
I have attached the GiD and .tcl files in a zip folder.

[Beam.gid.zip](https://github.com/rclab-auth/gidopensees/files/2261155/Beam.gid.zip)

**Comment by vpapanik** [comment]
You are using a way old version of the interface (2.2.5), why not update ?

**Comment by haldarsumanta** [comment]
Updated. However, it shows a similar error.

[Beam.gid.zip](https://github.com/rclab-auth/gidopensees/files/2262094/Beam.gid.zip)

**Comment by vpapanik** [comment]
There are some extra nodes that belong to nowhere. Do a 'repair geometry' and a 'collapse model' first, and it will work. Some coordinates are also not rounded, use a grid to draw. These issues are easily spotted in the .tcl file.

**Comment by haldarsumanta** [comment]
thanks @vpapanik. it is working now,
