### ISSUE TITLE
Download  GiD+OpenSees Interface

### ISSUE THREAD

**Issue by amersaied** [rclab-auth/gidopensees#52]
Dear
Please tell me how to download & install the recent version of  GiD+OpenSees Interface.
Beside, Can it do nonlinear analysis of concrete beams strengthened with GFRP sheets & showing the failure shapes & debonding between concrete & GFRP sheet.? Please give me a detailed answer. Thanks

**Comment by vpapanik** [comment]
https://github.com/rclab-auth/gidopensees/wiki/Getting-Started

**Comment by amersaied** [comment]
Dear Dr
Greetings
Please tell me:
1- I want to know that GiD+OpenSees has a better features related to
Seismostruct? what are the differences between both?
2- Please send me a tutorials for how to do nonlinear analysis for 3D
concrete  flat slab building under nonlinear dynamic time history loading
by GiD+OpenSees?



*Thanks & Best Wishes Dr. Amr Masoud*
Egyptian National Research Center
Mobile: 002-01550412610
amrhbrc@gmail.com
