### ISSUE TITLE
Simulation of displacement controlled Cyclic Triaxial Test

### ISSUE THREAD

**Issue by haldarsumanta** [rclab-auth/gidopensees#54]
I am trying to simulate displacement controlled cyclic triaxial test using GiD Opensees. The initial phase of loading is hydrostatic pressure. The second phase (deviatoric) will be cyclic displacement (sinusoidal). I am unable to simulate using GiD-OpenSees interface. It this possible? If yes, how?

**Comment by vpapanik** [comment]
Probably yes, don't know what exactly your model may look like. Please read the user manual thoroughly first.

https://github.com/rclab-auth/gidopensees/wiki

**Comment by haldarsumanta** [comment]
Alright, I will check. Is it possible to include other material models in GiD? I want to include Drucker Prager, Manzari Dafalias model for analysis which is already available in OpenSees.
