### ISSUE TITLE
can not run analysis

### ISSUE THREAD

**Issue by naderhov** [rclab-auth/gidopensees#55]
Dear gid Opensees team
I am a new user to gid opensees. I am trying to perform an analysis using an example of site, however, there is a problem. When I perform analysis, I encounter a problem, saying that :could not run the analysis, please check generated tcl file!
any help appreciated...
thanks

**Comment by rrodriguez252** [comment]
HI. I am also having the same issue. The program is outputting

"invalid command name "model" while executing "model" basicBuilder -ndm 2 -ndm 3"
(file "C\Users..."
line 62.

Thanks

**Comment by rrodriguez252** [comment]
I believe to fix this error you have to save OpenSees in the C:\ location as instructed during installation. Uninstall and reinstall GiDOpenSees. The only error I am receiving now is:

GiD_AccessValue: property Use_HDF5_binary_output_format not found in  GenData
GiD_AccessValue: property Use_HDF5_binary_output_format not found in  GenData
    while executing
"GiD_AccessValue get GenData Use_HDF5_binary_output_format"
    (procedure "ExecutePost" line 19)
    invoked from within
"ExecutePost"
    (procedure "CheckLogAndPost" line 46)
    invoked from within
"CheckLogAndPost $GiDProjectDir $GiDProjectName $doPost"
    (procedure "Run_existing_tcl" line 21)
    invoked from within
"Run_existing_tcl $w $true"
    (procedure "Run_existing_tcl_and_postprocess" line 6)
    invoked from within
"Run_existing_tcl_and_postprocess $w"
    (procedure "Create_tcl_run_analysis_and_postprocess" line 24)
    invoked from within
"Create_tcl_run_analysis_and_postprocess .gid.warn1"
    invoked from within
".gid.warn1.bottom.continue invoke "
    invoked from within
".gid.warn1.bottom.continue instate !disabled { .gid.warn1.bottom.continue invoke } "
    invoked from within
".gid.warn1.bottom.continue instate pressed { .gid.warn1.bottom.continue state !pressed; .gid.warn1.bottom.continue instate !disabled { .gid.warn1.bott..."
    (command bound to event)

**Comment by vpapanik** [comment]
Well, all these error are caused by leftovers from previous versions. Please use the latest GiD version which is 14.0.1. Delete the problemtypes/OpenSees folder and try to install the interface again. Then, all will work fine.

**Comment by vpapanik** [comment]
Please also ensure that there's a text editor associated with the .tcl extension in windows.
