### ISSUE TITLE
Import Geometry from existing .tcl 

### ISSUE THREAD

**Issue by sadeghebrahimi** [rclab-auth/gidopensees#56]
Dear GiDOpenSeeS team

First of all, I should appreciate your efforts for providing this helpful graphical interface.

I have a problem with importing .tcl files. The first option in "Gid+OpenSees" tab.
I tried many .tcl files but each time I encountered with this error : "Could not import model geometry".

Finally, I made a simple model to attach here (single quad element).

I would be grateful If you could check my .tcl file and explain me why I cannot import geometry from a .tcl file.

I really appreciate your consideration.
[single quad element.zip](https://github.com/rclab-auth/gidopensees/files/2344296/single.quad.element.zip)

**Comment by vpapanik** [comment]
Hello, and thanks for testing the new tcl import feature. The file you sent works fine. Please send us all your tcl files that do no work in order to test them and fix any possible bugs on the way.

**Comment by sadeghebrahimi** [comment]
Hello

I really appreciate your answer and consideration.
I cannot import any tcl files as similar as the file I've sent for you. However, you said "The file you sent works fine". Thus, I think the problem does not relevant to the tcl file.
I tried new version of Gid, OpenSees, and ActiveTcl but the problem was not solved.
I always encounter with the error which I attached it.
I would be really grateful If you help me for solving this problem.
![import failed](https://user-images.githubusercontent.com/42925474/44998965-0910ff00-afcf-11e8-96db-a2a83769010e.JPG)

**Comment by sadeghebrahimi** [comment]
I attached two another tcl files. One of them is a single 2D soil column and the another one is 3D soil elements with a circular pile. As I said before, I cannot import them to the OpenSees+GiD interface.

[single soil column.zip](https://github.com/rclab-auth/gidopensees/files/2346489/single.soil.column.zip)
[soil with circular pile.zip](https://github.com/rclab-auth/gidopensees/files/2346490/soil.with.circular.pile.zip)

**Comment by sadeghebrahimi** [comment]
Hello

I'm so sorry for my successive comments.
I also tried to import .tcl files from the examples on the GiD+OpenSees website (https://github.com/rclab-auth/gidopensees/wiki/Examples). However, I faced to that error again.
I attached the .tcl file relevant to the Example - Plane Frame - Dynamic Analysis.
This problem is confusing me!!

I really appreciate your consideration.
I'm looking forward to hearing from you.

[Plane Frame under dynamic analysis.zip](https://github.com/rclab-auth/gidopensees/files/2347495/Plane.Frame.under.dynamic.analysis.zip)

**Comment by vpapanik** [comment]
Just checked the last one and works for me. There have been some changes in tclImport.exe lately, so I am attaching the latest for you to check out.
[tcl_Import.zip](https://github.com/rclab-auth/gidopensees/files/2360765/tcl_Import.zip)

**Comment by sadeghebrahimi** [comment]
Dear Prof. Papanikolaou

I really appreciate your answer and consideration.

I downloaded the attached file. Then, in the following destination location  C:\Program Files\GiD\GiD 14.0.1\problemtypes\OpenSees.gid\exe , I replaced the first tcl_Import.exe file with the attached file. After that, I tried to import a .tcl file to the GiD+OpenSees interface but unfortunately I was faced with this error : "Could not find the main class: tcl_import_package.Main. Program will exit. "
![error](https://user-images.githubusercontent.com/42925474/45252361-2563c180-b36a-11e8-8eb3-3ac3f290368b.JPG)

**Comment by vpapanik** [comment]
Do you have the latest java installed on your computer ?

**Comment by sadeghebrahimi** [comment]
Hello 
I downloaded the latest version of Java and also replaced the old tcl_import file with the new one.
Finally, I could import a geometry from a tcl file successfully. 
I really appreciate you.
Best Regards

**Comment by vpapanik** [comment]
Thanks a lot for your feedback. Please still provide us with the models that do not work in order to check them.

**Comment by sadeghebrahimi** [comment]
I'll definitely do that. 
Thank you

**Comment by vpapanik** [comment]
No, it will be available on the next version. You can try downloading it from here for now.
