### ISSUE TITLE
post procceing

### ISSUE THREAD

**Issue by najjar1373** [rclab-auth/gidopensees#60]
hi,when i run this app ,it show this problem:
![untitled](https://user-images.githubusercontent.com/42331086/46418870-78e2e880-c739-11e8-9b0d-2dc09590fccb.png)
![untitled](https://user-images.githubusercontent.com/42331086/46418921-9617b700-c739-11e8-8bfd-dabe12049d0c.png)

**Comment by najjar1373** [comment]
i use gid opensees 2..6

**Comment by vpapanik** [comment]
Please attach your model in order to check it out. Thanks

**Comment by vpapanik** [comment]
No reply whatsoever, issue closed.
