### ISSUE TITLE
Assign restraints in node

### ISSUE THREAD

**Issue by shaikasharkia** [rclab-auth/gidopensees#61]
Hello. In my project, there are 2 nodes (say, node 3 and 4) at the same coordinate for creating a zero-length element. How can I assign restraints to 1 particular node? Each time I want to assign restraint by clicking on the node, it catches node 3. Thanks in advance for your time.

**Comment by vpapanik** [comment]
Sel;ect node 3 and put it in another layer. Then you can turn off that layer so you can catch node 4.

**Comment by shaikasharkia** [comment]
Thank you very much. 
Also, I found out that, selection window under the Utility menu works well.
