### ISSUE TITLE
Analysis could not run

### ISSUE THREAD

**Issue by cvdr888** [rclab-auth/gidopensees#63]
![sem titulo](https://user-images.githubusercontent.com/44230404/47082892-0973fb00-d207-11e8-8be1-5da14bfa5718.png)

This happens from a fresh install. What can I do about this error?
I have followed the instruction from the wiki install page.

Thanks

**Comment by vpapanik** [comment]
There's a problem with OpenSees itself. Have you also installed the tcl/tk framework ?

**Comment by vpapanik** [comment]
Have you checked the interface with any ready-to-run example ? there are a lot available in GitHub.

**Comment by cvdr888** [comment]
Yes... I've tried the examples from https://github.com/rclab-auth/gidopensees/wiki/Verification.
The error when I try to run them by pressing F5 key (menu Calculate>Calculate command)  is:
![1](https://user-images.githubusercontent.com/44230404/47270090-787e8600-d55e-11e8-91b6-b4e50cfc2c41.png)
The error I get when I select the GidOpensees>Run analysis and post-process is:
![2](https://user-images.githubusercontent.com/44230404/47270127-e62ab200-d55e-11e8-9d04-10aaa2644f85.png)
Also, my tcl file was generated with the option 'Create tcl only' because the option 'Run analysis and post-process' couldn't create the tcl file initially.

**Comment by vpapanik** [comment]
Well, there's been a mixup with previous versions of the interface. Completely delete OpenSees.gid folder from /problemtypes and reinstall the interface 2.6.0.

**Comment by vpapanik** [comment]
There's no reply whatsoever, so I consider this issue resolved.
