### ISSUE TITLE
Problem in opensees function file.

### ISSUE THREAD

**Issue by haldarsumanta** [rclab-auth/gidopensees#64]
Hi
I am trying to make a function file in opensees that can estimate the natural frequency of the soil-pile system. However, it shows a typical error "missing close brace". I have checked several times. Without function command, it is working perfectly fine. Can anyone help in this regard? File and error are attached.

![image](https://user-images.githubusercontent.com/42090501/47478640-b245da00-d847-11e8-9e27-ad49af902f57.png)
[getFrq.zip](https://github.com/rclab-auth/gidopensees/files/2513478/getFrq.zip)

**Comment by vpapanik** [comment]
You can post your question in the OpenSees forum, this place is only for the GiD+OpenSees interface.
