### ISSUE TITLE
Opening bracket missing in script for fiber custom

### ISSUE THREAD

**Issue by tejeswar91** [rclab-auth/gidopensees#67]
Hi found a small problem in scripting while using "fibre custom" in sections. Details are as attached.

Mistake Highlighted 
![image](https://user-images.githubusercontent.com/37624980/49326203-85dd5600-f589-11e8-9a30-fe63eef71500.png)

Corrected
![image](https://user-images.githubusercontent.com/37624980/49326207-a60d1500-f589-11e8-8517-391e09c082a3.png)

**Comment by vpapanik** [comment]
I think that the second open bracket is not needed at all, the first line is ok

*if(MatProp(Activate_torsional_stiffness,int)==1 && MatProp(Torsional_stiffness_GJ,real)!=0)
section Fiber *FiberCustomTag -GJ *MatProp(Torsional_stiffness_GJ,real)
*else
section Fiber *FiberCustomTag
*endif

**Comment by tejeswar91** [comment]
This is file comes with installation, I mean no open bracket in line number three


![image](https://user-images.githubusercontent.com/37624980/49363859-c241bb00-f71d-11e8-9b58-e9b204fbe8a2.png)
