### ISSUE TITLE
postprocess issues

### ISSUE THREAD

**Issue by yuziliunian** [rclab-auth/gidopensees#68]
After the model starts operation, prompt in DOS window that Analysis completed sucessfully，But in the GiD prompt that analysis could not run.

**Comment by vpapanik** [comment]
plz send your GiD model here to check

**Comment by yuziliunian** [comment]
The problem has been solved. I use Chinese as the name of the GiD project，  so the calculation results can not be postprocessed.

**Comment by vpapanik** [comment]
This is a common mistake, I also say to my students NOT to use Greek for filenames in GiD. It just doesn't work.
