### ISSUE TITLE
Copying w/ zerolength elements or fast way to create hundreds of zerolength elements

### ISSUE THREAD

**Issue by geobengineering** [rclab-auth/gidopensees#69]
I am attempting to model a 3D pile group with 100 beam column elements for each pile, and a pySimple1 zerolength element assigned at every pile node. With 20 piles in the group, there are thousands of py elements that need to get assigned. Using the "Assign ZeroLength Elements" window in GID+OS works, but is very slow because you have to select one pair of nodes and change the "ZeroLength ID" for every element. On the other hand, when I created one pile with all the py elements attached and then copied the whole thing ("Entities type: All types"), the zerolength elements don't copy properly; I end up with connections between my old pile and new pile nodes.

Any tips on how to copy zerolength elements so that the newly created element will only join the newly copied nodes? Or, how to speed up assigning them graphically?

The other option is of course to edit the TCL file directly, since I can automate the creation of script to generate the commands. But, then the elements are not a part of the GID model, so I can't view them in post-processing (unless I am missing something -- can I run OpenSeesPost.exe manually?)

From some of the other comments I imagine others are facing a similar issue when trying to add viscous damping to a 3D soil domain boundary.

Thanks,
Ben

**Comment by fereshteh2012** [comment]
Dear gid opensees interface team,

When I perform analysis, I encounter a problem, saying that :could not run the analysis, please check generated tcl file!
I work with the latest GID version 14.0.1 and interface version 2.6.0 and I delete the problemtypes/opensees folder to install interface again but it does'nt work.
any help appreciated...
thanks.
