### ISSUE TITLE
Gid need help 

### ISSUE THREAD

**Issue by mahaul** [rclab-auth/gidopensees#70]
please can someone tell the error I am getting 0 stress and deformation
[slope.zip](https://github.com/rclab-auth/gidopensees/files/2845238/slope.zip)

**Comment by fereshteh2012** [comment]
Dear gid opensees interface team,

When I perform analysis, I encounter a problem, saying that :could not run the analysis, please check generated tcl file!
I work with the latest GID version 14.0.1 and interface version 2.6.0 and I delete the problemtypes/opensees folder to install interface again but it does'nt work.
any help appreciated...
thanks.

**Comment by vpapanik** [comment]
use uniform excitation instead of function
