### ISSUE TITLE
Problem with Post-processing and use of undo option

### ISSUE THREAD

**Issue by shrbd** [rclab-auth/gidopensees#73]
[3-D Frame (Static & Modal Analysis-zip).gid.zip](https://github.com/rclab-auth/gidopensees/files/2868654/3-D.Frame.Static.Modal.Analysis-zip.gid.zip)

(The folder containing the all the files related to the model are zipped and uploaded above).
I am facing a problem with **postprocessing**, i.e. when the analysis is done the **GID window crashes** ("Opensees has stopped working"). After that, when I switch to postprocessing mode and check for deflection and results, the options are frozen, and it says "**please load a model first**." Please help in this regard.
![gid-2](https://user-images.githubusercontent.com/47659705/52849058-33e2b000-3136-11e9-9c14-3e55f5101a26.jpg)
![gid-3](https://user-images.githubusercontent.com/47659705/52849060-347b4680-3136-11e9-953b-629e74027145.jpg)
![gid-1](https://user-images.githubusercontent.com/47659705/52849063-3513dd00-3136-11e9-8fee-8e2987e845a3.jpg)

Apart from the above issue, during modeling, the **GID software also crashes** when I use the **undo option or ctrl+z.**

**Comment by vpapanik** [comment]
Try to run your .tcl file through command line. I am trying to run that way but Opensees seems to be stuck in eigenvalue analysis.
