### ISSUE TITLE
gid setup

### ISSUE THREAD

**Issue by mahaul** [rclab-auth/gidopensees#75]
i accidentally generated all 3 of my licences on the same day.
Can something be done?

**Comment by tejeswar91** [comment]
You can contact here for your issue "gid_sales@cimne.upc.edu". 

Or else if you want to know your previous passwords please fill required information here in this page "https://www.gidhome.com/purchase/passwords/" and submit. 

It will redirect to another page. Scroll down and you can see previously generated passwords for your system with the corresponding date. 

Hope it will help.

**Comment by vpapanik** [comment]
This has to do with the GiD license part, so you have to contact them for resolving the issue.
