### ISSUE TITLE
Problem in applying P-Delta and Bond-slip in Time history analysis

### ISSUE THREAD

**Issue by atanusantra1991** [rclab-auth/gidopensees#76]
In my recent research work, I am using your software Gid+Opensees Interface v2.6.0. I am trying to apply P-delta and Bond-slip effect in a column section for time history analysis using a sample ground motion acceleration. But there are not affecting the results. Three cases has been performed: (i) without P-delta and Bond-Slip, (ii) With only P-delta, (iii) With both the P-delta and Bond-slip. The files are attached here. The results are also attached where it can be seen that, all cases gives same displacement history. So, both the P-delta and Bond-slip are not functioning in these files.

Therefore, I will be highly obliged, if you kindly look into the matter and help me with what are the errors in these files and how those can be fixed.

[files.zip](https://github.com/rclab-auth/gidopensees/files/2899302/files.zip)

**Comment by vpapanik** [comment]
Compare the .tcl files from each case and spot on the differences. It should be a clear OpenSees issue, not an interface one. If you find out that there are certain data in the GiD model which are not correctly transferred to the .tcl file please report back.
