### ISSUE TITLE
Missing OpenSees.bat file

### ISSUE THREAD

**Issue by Thivya5895** [rclab-auth/gidopensees#77]
Hello,

I'm getting the error message that the file OpenSees.bat in my GiD programm directory is missing. If I use the calculation button on the right menu, I get the message that the analysis could not run. Does anybody has an idea what the problem might be?

Kind regards

Thivya

**Comment by vpapanik** [comment]
The correct way to work is either from the button or the Opensees menu, not the Gid standard menu. If the analysis cannot run, then there's a problem with the model itself.

**Comment by Thivya5895** [comment]
Thank you for your reply. I tried to run the tcl file only with OpenSees and get the error message:
WARNING invalid nodeId: C:/Program Files/Tcl/lib/tcl8.5/reg1.2/tclreg12.dll - load nodeId 1 forces
Do you have an idea what may cause this problem? I guess it's not only node 1 but all of them.

Kind regards

Thivya

**Comment by vpapanik** [comment]
ignore those 2 lines, it is not an error, just a known false message of OpenSees. The analysis should continue after that.
