### ISSUE TITLE
interval interrupted

### ISSUE THREAD

**Issue by fereshteh2012** [rclab-auth/gidopensees#78]
Hi,
when I perform analysis in the third interval, (which is dynamic analysis) is interrupted.
Loading type is uniform excitation.
could you please guide me?
![Capture](https://user-images.githubusercontent.com/47320355/54201725-9afc4600-44e3-11e9-84b0-9718fc1d5548.PNG)
thanks,

**Comment by vpapanik** [comment]
I can check it if you posted your model
