### ISSUE TITLE
extradosed bridge

### ISSUE THREAD

**Issue by carlosebernal** [rclab-auth/gidopensees#83]
Dear.
I am a student and I am working in GIDOPENSEES to model an extradosed bridge. I had problems assigning the cable element because I can not find the option in the interface. Someone could tell me the procedure to achieve it.
Thank you.

Estimados.
Soy estudiante y estoy trabajando en GIDOPENSEES para modelar un puente extradosado. He tenido problemas al asignar el elemento cable debido a que no encuentro la opción en la interfaz. Alguien me podría indicar el procedimiento para lograrlo. 
Gracias.

**Comment by vpapanik** [comment]
For the moment, cables are not implemented in the interface, but it will be added in the future. If you do any development yourself, please let us know.
