### ISSUE TITLE
Problem in Ground Motion Peer Format

### ISSUE THREAD

**Issue by MedSaadMor** [rclab-auth/gidopensees#84]
in the record windows, while insering AT2 file or either Dat file, and requesting display record,  i have a message "can't convert 0.01 serie to double" or "input serie format is wrong" 

need help by giving me example of a working record format so i can stick to it.

thanks

**Comment by theokart** [comment]
make sure your file meets the format you selected, and do not forget to update window to update changes before displaying recond

**Comment by vpapanik** [comment]
Please report back whether you have solved the problem

**Comment by MedSaadMor** [comment]
Problem solved, in fact "." is considered as a string so as an alternative i convert the input serie to scientific format.

**Comment by vpapanik** [comment]
check your system settings. Maybe you have a comma as a decimal delimiter.
