### ISSUE TITLE
MinMax element Bas file error

### ISSUE THREAD

**Issue by Maffy92** [rclab-auth/gidopensees#89]
https://github.com/rclab-auth/gidopensees/blob/ed4cf8aadf523c9d580e181c6788c3c38a5cc371/bas/Materials/Uniaxial/MinMax.bas#L5

Line 5 one parenthesis Missing.

And when the model is executed with Mimax element, an error message comes saying, "Error in base file 'C:/Program Files/GiD/GiD 14.0.2/problemtypes/OpenSees.gid/bas/Sections/../Materials/Uniaxial/MinMax.bas' at line number 33: Bad real format"

I don't understand what error is there..Please correct this.

**Comment by vpapanik** [comment]
Thanks for reporting this bug, it will be corrected in the upcoming update.
