### ISSUE TITLE
analysis failed due to expected identifier 

### ISSUE THREAD

**Issue by MedSaadMor** [rclab-auth/gidopensees#91]
could'nt be able to run analysis, warning message possibly show that's it can be about weight issue but i could'nt resolve the problem. thanks for advance for your assistance.

![image](https://user-images.githubusercontent.com/49350409/57494666-e5b6f600-72b9-11e9-8586-2054c6ec319c.png)

**Comment by vpapanik** [comment]
We can investigate further if you don't send your model
