### ISSUE TITLE
Analysis could not run!

### ISSUE THREAD

**Issue by peppdalo** [rclab-auth/gidopensees#93]
Dear Gid+OpenSees Interface team,
I tried to reproduce Tutorial 5 (Site Response Analysis of a Layered Soil Column) in Reference Manual, but i had a problem with analysis process running.
The analysis failed, an error message appeared and .tcl file was not generated. Could you take a look to to my model, please? Thank you.

[tutorial 5.gid.zip](https://github.com/rclab-auth/gidopensees/files/3220430/tutorial.5.gid.zip)

**Comment by vpapanik** [comment]
You used quadrilateral elements on a triangular mesh. Either change the mesh type or the element type.
