### ISSUE TITLE
Response from two different nodes

### ISSUE THREAD

**Issue by benissimo90** [rclab-auth/gidopensees#94]
First of all: Many thanks for the great work that the AUTh team has done here. 
To my question: How can I plot (for example) the deformation of the node a in Ux and the acceleration of the node b in ax in a time history analysis? Or I use a specific function as record (for example node force at the head of a beam) and want to record function value (not time) against an effect (N/M/V...)?

Thank you very much for your answers!
Greetings
Benjamin

**Comment by vpapanik** [comment]
These features are included in the GiD postprocessor itself, check the GiD manual
