### ISSUE TITLE
Regarding use of zero length element for SSI problem

### ISSUE THREAD

**Issue by vasudeochaudhari** [rclab-auth/gidopensees#95]
Dear Team

To study the soil structure interaction during earthquake ground motion. Here a model needs to develop with soil as a spring (maybe using zero-length element) to support pile (typically model as element elasticBeamColumn). 

I kindly request you to suggest me a tutorial. 

Thanking you
Vasudeo Chaudhari

**Comment by vpapanik** [comment]
Check the wiki

"Download the introductory course notes and models from the 9th GiD Convention"

there is a tutorial and a model 'plane frame on elastic soil'

**Comment by cvdr888** [comment]
Hello, 
I am also trying to model a pile-soil interaction. Besides the continuum soil, I would like to try the ZeroLengthElement discrete option. 
I searched for your previous suggestion 'plane frame on elastic soil' in the GiD Convention. Unfortunately, I only found the 'Example B2 – Inelastic Plane Frame on Elastic Soil', that uses surfaces to model the soil. 
Can you send me the link for the model/tutorial, please?
Thanks,
CR.

**Comment by vpapanik** [comment]
That's exactly what you need, it doesnt matter whether the frame is elastic or inelastic, the process of connecting the frame with the elastic surface soil substrate is the same.

**Comment by cvdr888** [comment]
> That's exactly what you need, it doesnt matter whether the frame is elastic or inelastic, the process of connecting the frame with the elastic surface soil substrate is the same.



I understand that the elastic/inelastic frame can be easily changed. However, the problem is that the cited example doesn't include zero length elements. Only Quads that are coupled to the frame by master/slaves. 
I can't find any example/tutorial of Gid+Opensees using zero length elements. Can you please recommend/provide one?
Thanks,
CR.
