### ISSUE TITLE
PostProcess visualization Problem

### ISSUE THREAD

**Issue by Wizard994** [rclab-auth/gidopensees#96]
Hello,
I have a problem with postprocess visualization because I don't obtain the "image" the structure who I'm analyzing or better the structure doesn't appear in that. More specifically I don't get error message but easily I cannot see the results. How can I solve that?

P.s: I noticed that when the analysis is running, always appear a Warning. I've attached a couple of images to make the idea better: 

[Doc1.pdf](https://github.com/rclab-auth/gidopensees/files/3325869/Doc1.pdf)
[Doc2.pdf](https://github.com/rclab-auth/gidopensees/files/3325870/Doc2.pdf)

**Comment by vpapanik** [comment]
The warning is a bug from OpenSees, it doesn't matter. Please attach your model in order to check.
