### ISSUE TITLE
sección no primatica

### ISSUE THREAD

**Issue by carlosebernal** [rclab-auth/gidopensees#99]
hola a todos, estoy desarrollando un puente simplemente apoyado y me he encontrado con que las vigas cabezal cuenta con una sección no prismática, ¿Cómo puedo asignar esta sección?

Hello everyone, I am developing a bridge simply supported and I have found that the head beams have a non-prismatic section, how can I assign this section?

**Comment by vpapanik** [comment]
Use a general sections with calculated geometrical data (area, moment of inertia etc)
